### ISSUE TITLE
username is not an email address

### ISSUE THREAD

**Issue by yellius** [jobisoft/EAS-4-TbSync#103]
Hello,
I believe my company uses account usernames that are not email addresses (judged by looking at my iphone account settings), however eas-4-tbsync doesn't allow testing that. Your help is very welcome!
Thanks,
  Jelle.

## Your environment

TbSync version: latest
EAS-4-TbSync version: latest
Thunderbird version: latest

[ ] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/EAS-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
...

## Actual behavior
...

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
If you select "custom configuration", you can enter whatever you want as username. Only during automatic configuration, it must be an email address, because the EAS account discovery process is based on email addresses.

From what you are reporting, your server may not support EAS, but only EWS, which is a different Exchange protocoll.

**Comment by yellius** [comment]
Thanks for that. If I select "custom configuration" I can indeed use another username, but my company uses 2FA which I guess is only supported through the "Microsoft Office 365" option that needs a proper email address?

**Comment by jobisoft** [comment]
Correct. If your company is using office 366, azure AD or hybrid setup it might work (with an email as user name) If it is a on premise server I guess it will not work at all.
