### ISSUE TITLE
Feature request: Kerberos support for on-premise Exchange servers

### ISSUE THREAD

**Issue by arjan-s** [jobisoft/EAS-4-TbSync#106]
## Your environment

TbSync version: 2.10
EAS-4-TbSync version: 1.11
Thunderbird version: 68.5.0

[ ] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/EAS-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
While setting up the synchronisation, the plugin authenticates to the on-premise Exchange server with my valid Kerberos ticket.

## Actual behavior
Kerberos is not supported by the plugin, which instead always asks for a password.

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Hi,

are you 100% sure, your server supports EAS with Kerberos tickets? I have never seen that before. EAS is different from EWS, what most on-premise Exchange server use.

I have enabled Kerberos support for my DAV provider, so I know I can add that feature. However, this will be basically just for you and I would have to ask you to fund about 4h of work to get this started. 

If you agree, please - again - keep in mind, that this is EAS and not EWS. EAS is less powerfull: You will not get access to shared resources with my EAS provider.

**Comment by arjan-s** [comment]
Well, that's spot on. I don't know whether my company's Exchange supports EAS, let alone EAS+Kerberos. I arrived at your addon after searching for ways to sync/access Exchange contacts and possibly calendar from Thunderbird. It seems yours is the only one that's working and maintained.
I'll do some homework before coming back here.

**Comment by jobisoft** [comment]
Any news?

**Comment by arjan-s** [comment]
Yes, EAS is indeed not supported. So instead I opted to use davmail, which supports Exchange with Kerberos and provides open protocols like LDAP and CalDAV that can be used in Thunderbird.
