### ISSUE TITLE
EAS-4-TbSync doesn't show contacts correctly on Thunderbird Contacts Catalog

### ISSUE THREAD

**Issue by joaopaulo1511** [jobisoft/EAS-4-TbSync#107]
## Your environment

TbSync version: 2.10
EAS-4-TbSync version: 1.11
Thunderbird version: 68.5.0 64 bit on Windows 10

[X] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/EAS-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Thunderbird Contacts Catalog main window should show all information on selected tabs (name, e-mail, organization etc.).

## Actual behavior
Thunderbird Contacts Catalog main window only shows telephone information.  It shows the other selected tabs information if any contact is edited to add "Show contact as" information (this is an easy workaround).

## Steps to reproduce
1. Add a Hotmail account using EAS.
2. Select to sync contacts.
3. Sync contacts.
4. Go to Mozilla Thunderbird Contacts Catalog and open your Hotmail address book.
5. Verify that only the commercial telephone is shown on all lines that represents each contact you have (if a contact has it).
6. Verify that changing the selected contact may or may not change the shown info on the pane below.
7. Edit a contact to add the info "present as".  I changed a contact "Arianna" which had first name as "Arianna", no last name, to be presented as "Arianna" (this is unnecessary, as Thunderbird would show as "Arianna" anyway).
8. Verify that all or almost all contacts are now shown properly on the Mozilla Thunderbird Contacts Catalog.

I have added some files with other steps and results on my screen.

1. 1st contact selected, e-mail wrong on the pane, telephone correct on the pane:
![1  1st contact selected, e-mail wrong on the pane, telephone correct on the pane](https://user-images.githubusercontent.com/5490558/74771896-62bdc580-5265-11ea-9b5c-941bebd590e0.png)

2. 2nd contact selected, e-mail wrong on the pane, telephone correct on the pane:
![2  2nd contact selected, e-mail wrong on the pane, telephone correct on the pane](https://user-images.githubusercontent.com/5490558/74771893-618c9880-5265-11ea-8a80-0b0a8d45eb6d.png)

3. 1st contact editted to add a 'present contact as' name:
![3  1st contact editted to add a 'present contact as' name](https://user-images.githubusercontent.com/5490558/74771888-5fc2d500-5265-11ea-9b0b-718020322f14.png)

4.  After saving the 'present contact as' name, almost all contacts are shown, but the info on the pane is still wrong:
![4  After saving the 'present contact as' name, almost all contacts are shown, but the info on the pane is still wrong](https://user-images.githubusercontent.com/5490558/74771882-5df91180-5265-11ea-9f38-975b96fbbc09.png)

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
That is standard behaviour and you can reproduce that with the standard addressbook ("Catálogo...pessoal" in your screenshoot). You must enter a value in "present contact as" or a primary email address to have an entry in the list.

On picture nr. 4, what is wrong? It shows the name, doesn't it? The pane does not show first and last name.

**Comment by jobisoft** [comment]
Wait, something is wrong with that email, only saw that now. 

Did you move contacts via drag'n'drop from some other Thunderbird address book (contacts catalog) into that Hotmail address book? Or is this directly the state after you synced your hotmail address book from the server to Thunderbird (initial sync)?

**Comment by jobisoft** [comment]
There was an issue related to this, which has been fixed. Could you check if this is fixed now as well?

Please force update your add-ons via the gear menu in the Thunderbird add-on manager and then disable all your TbSync accounts in the TbSync manager and re-enable them to start fresh.

Do you still have that broken behaviour?

**Comment by joaopaulo1511** [comment]
Sorry for my late answer, because of the Covid-19 pandemic I was busy trying to be safe, keep my parents safe, still work and being mentally healthy, so I wasn't paying attention to Github.

> On picture nr. 4, what is wrong? It shows the name, doesn't it? The pane does not show first and last name.

Picture 4 is not wrong, it is the only picture that shows all the fields that were mapped to the columns under the "Edit Contact" dialog.  I don't know why, but seems to be needed to edit a contact (I edited the "show as / present as" field -- I don't know if I translated back to English correctly) so the lines representing contacts on that window under "Edit Contact" dialog would show up.

> Did you move contacts via drag'n'drop from some other Thunderbird address book (contacts catalog) into that Hotmail address book? Or is this directly the state after you synced your hotmail address book from the server to Thunderbird (initial sync)?

No, I didn't moved via drag'n'drop.  It is the state after the initial sync to my Hotmail address book.

> There was an issue related to this, which has been fixed. Could you check if this is fixed now as well?
> 
> Please force update your add-ons via the gear menu in the Thunderbird add-on manager and then disable all your TbSync accounts in the TbSync manager and re-enable them to start fresh.
> 
> Do you still have that broken behaviour?

I will check if the issue was fixed and will send a message soon.

**Comment by jobisoft** [comment]
In Thunderbird 102 I no longer manipulate the contact panel view. Sorry that I was not able to fix this in 91 or before, but now the issue no longer applies and I will close this issue.
