### ISSUE TITLE
Events created/changed by TbSync contain trailing Zeros in TimeZone when exported in OWA

### ISSUE THREAD

**Issue by Flamefire** [jobisoft/EAS-4-TbSync#110]
## Your environment

TbSync version: 2.11
EAS-4-TbSync version: 1.12
Thunderbird version: 68.5.0

[x] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/EAS-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
TimeZone is correctly set and exportable without trailing Zeros

## Actual behavior
TimeZone contains trailing zeros

## Steps to reproduce
- Create Event in ThunderBird
- Sync with TbSync to Ms Exchange
- Go to OWA (Office Web Access)
- Forward created event to email
- Observe contained iCal

Some example data of that iCal (after base64 decode):
```
BEGIN:VCALENDAR
METHOD:PUBLISH
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
BEGIN:VTIMEZONE
TZID:W. Europe Standard Time���������
BEGIN:STANDARD
DTSTART:16010101T020000
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T010000
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
ORGANIZER;CN="Grund, Alexander":MAILTO:foo@bar.de
SUMMARY;LANGUAGE=de-DE:FOO
DTSTART;TZID=W. Europe Standard Time���������:20200322T190000
DTEND;TZID=W. Europe Standard Time���������:20200322T200000
UID:45d438d8-3952-41bc-ac03-1365a49c3f17
CLASS:PERSONAL
PRIORITY:5
DTSTAMP:20200317T171155Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION;LANGUAGE=de-DE:
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-OWNERAPPTID:2118356093
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-DISALLOW-COUNTER:FALSE
BEGIN:VALARM
DESCRIPTION:REMINDER
TRIGGER;RELATED=START:-PT10M
ACTION:DISPLAY
END:VALARM
END:VEVENT
END:VCALENDAR
```

This is after I changed the source to

            easTZ.standardName = "W. Europe Standard Time";
            easTZ.daylightName = "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna";

in an attempt to fix this. I obviously failed. Observe the � above (which are unprintable NULL bytes)

This is the same issue as https://github.com/jobisoft/TbSync/issues/187 which is where I got the idea from to avoid a slash in the timezone. E.g. DavMail converts standard timezones (like "Europa/Berlin") to exchange timezones (like "W. Europe Standard Time"), see http://davmail.sourceforge.net/xref/davmail/exchange/VCalendar.html#L374. This might be a good idea to do anyway.

I'm out of ideas actually. I tried various things and inspected transferred stuff but everything looks good until the iCal. Creating an event in OWA and forwarding that does not contain those Zeros.

**Comment by jobisoft** [comment]
I will have a look.

**Comment by Flamefire** [comment]
Some good news: At least ThunderBird 75.0 will be able to handle invites to such events: https://bugzilla.mozilla.org/show_bug.cgi?id=1623896

If there is anything found why the NULLs land in there it would be best. And probably add the timezone name translation

**Comment by jobisoft** [comment]
Nice work on the patch! You can request uplift to beta by yourself setting the ESR request flag. This will fix this issue here completely right? Do we still need to convert the timezone names? The IANA names to MS names conversion is not 1-to-1...

**Comment by jobisoft** [comment]
I think you first need to get it into beta and than into ESR...

**Comment by Flamefire** [comment]
Not really. It is still weird that the NULLs are there in the first place as this is not the case for events created in OWA. Could be a MS bug of course.

> Do we still need to convert the timezone names

Not sure how they are used anyway. But I'd say yes to avoid any issue related to that. I'd just do what that calDAV thing is doing as it has some field experience already.

> I think you first need to get it into beta and than into ESR...

Sorry don't understand this. Never used their bugtracker before... My problem is: On Linux I'm (kinda) stuck on 68 so I need the fix (here or in TB) for that version too.

**Comment by jobisoft** [comment]
I just looked at the bug and they changed the flag system, so i do not know how this works now. It looks like it is set for uplift to esr68 already, but it is closed, which is strange. I will try to get this sorted out.

Will look at the timezone naming stuff as well.

**Comment by jobisoft** [comment]
In the current beta I now translate IANA timezone names to Windows timezone names. Wanna give it a spin?
https://tbsync.jobisoft.de

This only affects new and modified events synced from TB to Exchange.

This should fix this and the other issue, right?

**Comment by jobisoft** [comment]
FYI: Relevant commits:
* https://github.com/jobisoft/EAS-4-TbSync/commit/5419dcd0f162ade99bde6c3358c6115af34fd93d
* https://github.com/jobisoft/EAS-4-TbSync/commit/d1c28cf06716a30fbfcc8201a129788bba2ffcb7

**Comment by Flamefire** [comment]
Will check monday.

> This should fix this and the other issue, right?

Not sure which you mean. It will solve the different name for the main TZ (OWA uses a different one for daylight saving TZ, but well...) but likely not the NULLs. Will see when I have access to the other comp

**Comment by Flamefire** [comment]
It kind of works. This is before going through OWS, just creating an event with some participant and checking the sent mail. 

> BEGIN:VTIMEZONE
> TZID:Europe/Berlin

The one in OWS contains the NULLs again (expected, already tried just changing the TZID):

> BEGIN:VTIMEZONE
> TZID:W. Europe Standard Time���������

**Comment by jobisoft** [comment]
Why did you get the IANA timezone name and not the Windows timezone name? I do not send the IANA names anymore. I do not understand,

**Comment by Flamefire** [comment]
I guess this is from TB itself: The event is created with IANA TZ and sent as such to participants. Only the upload to MSX via TbSync will have the MS TZ. So this is expected.

**Comment by jobisoft** [comment]
Could you check what happens to a normal event that you create in TB and sync that to MS and export it from OWA?

**Comment by Flamefire** [comment]
That is the second example above. Sorry if this wasn't clear. So it syncs IANA to MSX and MSX (likely) fails to remove the NULLs when converting

**Comment by Flamefire** [comment]
Just an idea: Previously I was using https://github.com/ExchangeCalendar/exchangecalendar until TB 68 changed the plugin system.

There I didn't notice those issues. It seems they are using a different protocol (plain XML? BXML?) which MS seemingly handles better as the problem with trailing zeroes cannot exist in the first place.

Have you ever considered using that?

**Comment by jobisoft** [comment]
No :-) Because it is a different protocol. I need EAS. EWS is an entire different thing.

**Comment by jobisoft** [comment]
My TB updated to 68.7 and according to this comment
https://bugzilla.mozilla.org/show_bug.cgi?id=1623896#c10

The bug has been backported? cqan you test?

**Comment by Flamefire** [comment]
Hasn't arrived at the PPA yet, so can't right now. It's great that at least that has happened which mitigates the issue partially. But I've noticed other parts of TB suffer from the same issue of converting length-containing strings to NULL-terminated strings loosing the data of such events (e.g. when going via calDAV)

I also opened an issue at a MS forum: https://social.msdn.microsoft.com/Forums/en-US/6de4c213-ff7c-40e4-a37a-dda43d73a156/events-created-via-eas-contain-embedded-nulls-in-the-timezone-field-when-exported?forum=os_exchangeprotocols

**Comment by guillaume-perreal** [comment]
This is still happening with Thunderbird 91 & EAS-4-TbSync 2.0.1.

When I create a calendaar and an event using OWA, the downloaded ICS is ok.

```
DTSTART;TZID=Romance Standard Time:20220707T120000
DTEND;TZID=Romance Standard Time:20220707T123000
```

Once I edit the event using Thunderbird and push it back to the server using TBSync, the TZID is padded with zeroes (symbolized as `^@`). This causes the calendar to become unusable with other calendar systems (like Google Calendar) :

```
DTSTART;TZID=Romance Standard Time^@^@^@^@^@^@^@^@^@^@^@:20220707T120000
DTEND;TZID=Romance Standard Time^@^@^@^@^@^@^@^@^@^@^@:20220707T130000
```

Should I open a new issue ?

**Comment by guillaume-perreal** [comment]
See https://github.com/jobisoft/EAS-4-TbSync/issues/168
