### ISSUE TITLE
Synced calendar events are changed into "private"

### ISSUE THREAD

**Issue by rg-user** [jobisoft/EAS-4-TbSync#113]
## Your environment

TbSync version: 2.10
DAV-4-TbSync version:
Thunderbird version: 68.4.2 (32-bit)

## Expected behavior: 
a) I add an event to my calendar; 
b) it gets synced to all devices; 
c) I can see the event details myself. 

## Actual behavior
a) and b) work; 
c): I can no longer see the event details myself (and nobody can); instead, I only see "private" event. 

This does not occur if I add the tag "public" to the event in a). 

I wonder what kind of information tbsync sends on this tag/attribute? Is there a way how I can set the "public" tag as default in lightning or Tbsync?

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).
--> there is no error occuring.

**Comment by jobisoft** [comment]
_I went through all the relevant documentation and TbSync is following the rules. One of your other devices is messing this up. It looks like it cannot cope with the "Personal" sensitivity setting, which I use as default, if neither Public nor Private is selected:_

_https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-ascal/9c2b9eec-cb79-4195-876d-d933c9043cbf_

_Furthermore the broken client should not remove access to the details for the owner._

**However**, I do see that Office 365 is only using Public and Private. I therefore switched the default setting to Public if none is selected. I included that change in my beta release channel. 
https://tbsync.jobisoft.de

If I get positive feedback from you, I will push this to the stable version as well.
