### ISSUE TITLE
Calendar invites are not sent out correctly & are not present in Exchange

### ISSUE THREAD

**Issue by nrodday** [jobisoft/EAS-4-TbSync#115]
## Your environment

TbSync version: 2.12
EAS-4-TbSync version: 1.14
Thunderbird version: 68.6

[x ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
I invite people to a meeting and they get an invite with the desciption in the body part. Also the appointment should be synced with Exchange such that I can see it in my OutlookWebApp.

## Actual behavior
When I send out calendar invites, other people receive the invite but without a body (e.g. content information is missing). Also the meeting simply doesn´t show up in the Outlook WebApp as if it wasn´t synced with Exchange.

Is this still unimplemented functionality?

**Comment by jobisoft** [comment]
That is currently not suported. Just search the open issues, there is one that is identical.
