### ISSUE TITLE
Missing release for 1.13

### ISSUE THREAD

**Issue by cvoltz** [jobisoft/EAS-4-TbSync#116]
Version 1.13 is available for download from the [Thunderbird Add-ons](https://addons.thunderbird.net/en-US/thunderbird/addon/eas-4-tbsync/versions/?page=1#version-1.13) site but there is not a corresponding release on the project's [releases](https://github.com/jobisoft/EAS-4-TbSync/releases) page. There is also no tag for the code in the release. This may cause users to believe that the 1.13 update is not a real release but is instead a trojan release from a hacked account. Please tag the code with the release number and update the releases page when generating a release so users can have some confidence it is a legitimate release.

BTW, thanks for your efforts on this project.

**Comment by jobisoft** [comment]
I added a tag for the latest release v1.14 (which has a typo in its commit message).
I no longer do "releases" on github, I just forgot to remove 1.12.

All good?

**Comment by cvoltz** [comment]
OK. Thanks.
