### ISSUE TITLE
sync in past

### ISSUE THREAD

**Issue by maxs99** [jobisoft/EAS-4-TbSync#118]
Hello,
where can i set the period at office 365 sync in the past
the sync is currently only until october 2019

thx

**Comment by maxs99** [comment]
sorry 
found the mistake

**Comment by sphakka** [comment]
@maxs99, how did you solve it? I have the same problem with a corporate EAS instance.

**Comment by jobisoft** [comment]
There is an option in the one of the options tabs of the TbSync manager

**Comment by sphakka** [comment]
Thanks! I always forgot to check that option *before* the first sync ^^
