### ISSUE TITLE
EAS fails to handle reminder properly

### ISSUE THREAD

**Issue by edouardduliege** [jobisoft/EAS-4-TbSync#128]
## environment
TbSync version: 2.12
EAS-4-TbSync version: 1.14
Thunderbird version: 68.10.0 (OS : Fedora)

My emails, calendars and contacts are on a Zimbra instance (8.8.15_GA_3928.FOSS)

## Expected behavior
reminders are handled properly

## Actual behavior
1st observation
create an event on the Zimbra interface with an alarm
sync Thunderbird
cancel the reminder of that event on Tunderbird, sync
--> a second event is created on the Zimbra interface, without an reminder. the one with the reminder is still there.
Sync, now I have 2 events on the calendar, one with and one without reminder.
Both events can be deleted without problems.

2nd observation
I create an event form 2 to 3 pm with a reminder. I change the time (new time is now 5 to 6 pm) in Thunderbird, sync, I now have 2 events on the Zimbra interface: one from 2 to 3, one from 5 to 6.

**Comment by edouardduliege** [comment]
Hi, I am bumping this issue. I am willing to fund a development to create a workaround.

**Comment by jobisoft** [comment]
I cannot reproduce that. Do you have a software engineer at hand, who could have a look at it=

**Comment by edouardduliege** [comment]
It turns out this is a Zimbra linked issue: when I configure the addon to sync with my work account, which runs on a Exchange infrastructure, reminders are handled properly.

So this is not a bug. The workaround is rather easy: configure emails using imap, and calendars/contacts using CalDav and CardDav: https://wiki.zimbra.com/wiki/Accessing_Zimbra_Collaboration_Server_with_Thunderbird#Thunderbird_instructions
