### ISSUE TITLE
Support for group calendars

### ISSUE THREAD

**Issue by bertvandepoel** [jobisoft/EAS-4-TbSync#132]
## Your environment

TbSync version: 2.12
EAS-4-TbSync version: 1.14
Thunderbird version: 68.10.0

[ ] Yes, I have installed the latest available beta version from https://tbsync.jobisoft.de and my issue is not yet fixed, I can still reproduce it.
[X] My version of Thunderbird is sadly not compatible with the beta release

## Expected behavior
After enabling the account, I expected to see all calendars available to me on https://outlook.office365.com/calendar/view/month

## Actual behavior
All calendars under "My calendars" are available, but the automatically created group calendar based on the teams thread I've been added to is not available in the list.

Based on some searches online, it seems that shared and group calendars are a different protocol version or somehow very different from owned calendars and are therefore not available in TbSync right now. I could however not find a clear official source saying so. I was also wonder if indeed group calendars and shared calendars are identical, whether they indeed are problematic through being only available in a different protocol version, and whether support is at all in the future or not. 

I do have some coding skills, but I'm not sure if this is something I will be able at all to write a PR for. I'd first need to know what the situation is of course, before I can look into it.

Thank you for the great addon by the way!

**Comment by jobisoft** [comment]
Group/shared calendars are not supported by the EAS protocol. You need EWS or OWA for that. Try the owl add-on or the Exquilla add-on.

My beta works with current ESR 78.
https://www.thunderbird.net

**Comment by bertvandepoel** [comment]
I see, that makes sense why it's not possible. Too bad it's only available in paid addons, as I assume my university probably won't be willing to reimburse that. As a minor suggestion, as I see there's already a duplicate for this issue: could you perhaps mention this in the README or wiki? That way you're saved the time of having to answer the issue. Thank you for your time!

**Comment by jobisoft** [comment]
https://github.com/jobisoft/EAS-4-TbSync/wiki/What-about-access-to-shared-calendars-via-EAS%3F

**Comment by bertvandepoel** [comment]
I must admit it wasn't clear to me that calendars under "groups" were considered shared, but I get your point. Microsoft just made everything really confusing and really inconvenient for all of us.

**Comment by jobisoft** [comment]
With the latest 365 spin, "groups" became more prominent. When the wiki was set up, that term was not used much. I will add it.

**Comment by bertvandepoel** [comment]
Thanks! :)
