### ISSUE TITLE
TB 68?

### ISSUE THREAD

**Issue by sphh** [jobisoft/EAS-4-TbSync#134]
Is there any new release compatible with Thunderbird 68, because many of us are still stuck with TB 68, either because their Linux distribution has not updated yet or because they rely on add-ons, which have to been updated to mailextensions yet.

**Comment by jobisoft** [comment]
As I am also Thunderbirds add-on coordinator, could you list add-ons still missing?

I did not remove older releases for TB68, so you should be still good to go. But I do not backport.

**Comment by sphh** [comment]
I am currently running the last version available for TB 68, but run into a problem (EAS-4-TbSync does not recover, if the connection to the Exchange Server fails with status `OAuth 2.0 authentication server returned: {}` due to network problems, you have to disable and reenable the accounts affected). Before opening a new issue I noticed, that I do not have the latest update of EAS-4-TbSync, but that I cannot update …

Here is a list of add-ons which I use and where I could not find a version for TB 78 (no ordering on priority):

- https://addons.thunderbird.net/en-GB/thunderbird/addon/attach-from-clipboard/
- https://addons.thunderbird.net/en-GB/thunderbird/addon/calendar-tweaks/
- https://addons.thunderbird.net/en-GB/thunderbird/addon/custom-sync-interval/
- https://addons.thunderbird.net/en-GB/thunderbird/addon/enhanced-priority-display/
- https://addons.thunderbird.net/en-GB/thunderbird/addon/imap-received-date/
- https://addons.thunderbird.net/en-GB/thunderbird/addon/latex-it/ (Work in progress! Thanks for your help!)
- https://addons.thunderbird.net/en-GB/thunderbird/addon/lightning-colors-reminder/
- https://addons.thunderbird.net/en-GB/thunderbird/addon/lightning-invitation-notifier/
- https://addons.thunderbird.net/en-GB/thunderbird/addon/lookout-fix-version/
- https://mailredirect.sourceforge.io/installation.html
- https://github.com/adam-p/markdown-here/releases
- https://addons.thunderbird.net/en-GB/thunderbird/addon/more-snooze/
- https://addons.thunderbird.net/en-GB/thunderbird/addon/nostalgy/
- (https://addons.thunderbird.net/en-GB/thunderbird/addon/nostalgy_ng/)
- https://addons.thunderbird.net/en-GB/thunderbird/addon/quickfolders-tabbed-folders/
- https://addons.thunderbird.net/en-GB/thunderbird/addon/reply-to-multiple-messages/
- https://addons.thunderbird.net/en-GB/thunderbird/addon/send-later-3/
- https://addons.thunderbird.net/en-GB/thunderbird/addon/stop-ignoring-reply-to/
- https://addons.thunderbird.net/en-GB/thunderbird/addon/todotxt-extension/
- https://addons.thunderbird.net/en-GB/thunderbird/addon/toggle-quotes/
- https://addons.thunderbird.net/en-GB/thunderbird/addon/unmangle-outlook-safelinks/
- https://mailmindr.net/
- https://github.com/ExchangeCalendar/exchangecalendar
- https://addons.thunderbird.net/en-GB/thunderbird/addon/outgoing-message-format/

**Comment by jobisoft** [comment]
I sadly do not have the resources to work on TB68 version :-( It is EOL for me.

Thanks for the list of add-ons!

**Comment by jobisoft** [comment]
We have worked hard to support developers in updating their add-ons. As of today, the following add-ons of your list work with TB 102 (or have working alternatives):

- https://addons.thunderbird.net/en-GB/thunderbird/addon/attach-from-clipboard/ (works)
- https://addons.thunderbird.net/en-GB/thunderbird/addon/enhanced-priority-display/ (works)
- https://addons.thunderbird.net/en-GB/thunderbird/addon/latex-it/ (see markdown-here-revival)
- https://addons.thunderbird.net/en-GB/thunderbird/addon/lightning-invitation-notifier/ (works)
- https://addons.thunderbird.net/en-GB/thunderbird/addon/lookout-fix-version/ (works)
- https://mailredirect.sourceforge.io/installation.html (native support in TB102)
- https://github.com/adam-p/markdown-here/releases (https://addons.thunderbird.net/addon/markdown-here-revival)
- https://addons.thunderbird.net/en-GB/thunderbird/addon/more-snooze/ (works)
- https://addons.thunderbird.net/en-GB/thunderbird/addon/nostalgy/ (https://addons.thunderbird.net/addon/nostalgy_ng/versions/)
- https://addons.thunderbird.net/en-GB/thunderbird/addon/quickfolders-tabbed-folders/ (works)
- https://addons.thunderbird.net/en-GB/thunderbird/addon/send-later-3/ (works)
- https://addons.thunderbird.net/en-GB/thunderbird/addon/toggle-quotes/ (works)
- https://addons.thunderbird.net/en-GB/thunderbird/addon/unmangle-outlook-safelinks/ (works)
- https://mailmindr.net/ (works)

The following add-ons are really ancient, and we have not been able to update them:

- https://addons.thunderbird.net/en-GB/thunderbird/addon/calendar-tweaks/
- https://addons.thunderbird.net/en-GB/thunderbird/addon/custom-sync-interval/
- https://addons.thunderbird.net/en-GB/thunderbird/addon/imap-received-date/
- https://addons.thunderbird.net/en-GB/thunderbird/addon/lightning-colors-reminder/
- https://addons.thunderbird.net/en-GB/thunderbird/addon/reply-to-multiple-messages/
- https://addons.thunderbird.net/en-GB/thunderbird/addon/stop-ignoring-reply-to/
- https://addons.thunderbird.net/en-GB/thunderbird/addon/todotxt-extension/
- https://github.com/ExchangeCalendar/exchangecalendar (try OWL or TbSync or ExQuilla)
- https://addons.thunderbird.net/en-GB/thunderbird/addon/outgoing-message-format/

I do not see that there will be more progress on these, so I will close this issue now.
