### ISSUE TITLE
Contacts from mailcow do not contain "Display Name"

### ISSUE THREAD

**Issue by marek-cerny** [jobisoft/EAS-4-TbSync#135]
## Your environment

TbSync version: 2.18
EAS-4-TbSync version: 1.20
Thunderbird version: 78.4.0

## Actual behavior
When Thundebrid with TbSync is connected to a Mailcow mail server (most up-to-date version) via EAS, contacts do no contain "Display Name" atribute. It looks like the attribute is not fetched from the server, it's always blank. When I edit a contact in TB and fill some value in the "Display Name" atribute, it *is* synchronized to the server. But it's once again omitted when I try to synchronize the same contact back to TB (new TbSync profile) from the server.

When I connect to the same mail server with TbSync/DAV-4-TbSync instead, everything is synchronized properly in both directions.

The issue might be either in EAS-4-TbSync or Mailcow itself, but I did not find a way how to narrow that down.

Maybe soneone encountered the same issue?

**Comment by jobisoft** [comment]
enable debug logging in tbsync manager help and do a clean sync from your server down to your thunderbird and check if your server sends the displayname property. You can see the name of that property, when uploading a contact to oyur server. (I would have to look it up)

**Comment by mlq** [comment]
As I am experiencing the same issue with a Mailcow instance, I will follow up here. It looks like that SOGO does not send the `FileAs` field with the entry that represents the display name. In contrast, I've tested it against an OWA server where I receive the field. I've opened a issue in the SOGO bug tracker.

**Comment by mlq** [comment]
Issue should be fixed with https://github.com/inverse-inc/sogo/commit/2826c83fc52f6aae5a90e02ca9bc166baf3057e2

**Comment by jobisoft** [comment]
Nice.

**Comment by mlq** [comment]
Issue has been fixed in mailcow as well: https://github.com/mailcow/mailcow-dockerized/issues/3928 - So this issue can be closed :smiley:

**Comment by jobisoft** [comment]
🥇
