### ISSUE TITLE
Meeting invitees are not shown

### ISSUE THREAD

**Issue by AshokChava** [jobisoft/EAS-4-TbSync#137]
## Your environment

TbSync version: 2.19
EAS-4-TbSync version:1.2
Thunderbird version:78.6

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
When I create a new meeting invite using the TbSync the invitee list should be shown when I access my calender on outlook

## Actual behavior
I don't get to see the invitees in the outlook even after syncing multiple times on TbSync side and outlike side.

## Steps to reproduce
- Create a meeting invite in office 365 calendar using TbSync EAS provider add user1 and user2
- Goto outlook and try seeing invitees in the meeting invite you won't be able to see them
- Also the invitees also won't be able to see the invitee list on outlook.
- But we have observed is applet calender it is showing the details fine.

To help to resolve your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by fthommen** [comment]
Same issue here.  The situation is even worse: Since attendees/invetees are not pushed to Exchange, Exchange only registers those attendees which either accept or deny the meeting. Those who don't react (which often is the major part) are not registered.  Only the Exchange-registered attendees are then synchonized back to the client (Thunderbird).  This results in the local client "loosing" attendees.  Those lost attendees will also not be notified about changes in description or the schedule of the meeting :-(

**Comment by jobisoft** [comment]
This is communicated as not being supported at all. If you need that, you will have to switch to owl. Or someone has to implement it in TbSync.

https://github.com/jobisoft/EAS-4-TbSync/wiki/About:-Provider-for-Exchange-ActiveSync

**Comment by fthommen** [comment]
Sorry to hear.  Unfortunatly Owl is not an option.  It seems unreliable and Beonex support never answered any of my requests.  TbSync was our last hope for finding a connection between TB and Exchange. :-(

**Comment by jobisoft** [comment]
Sorry to hear that. But TbSync aims at private users, as I am a single person and not able to fulfill professional needs and support.

**Comment by fthommen** [comment]
That's ok.  That wasn't meant as critism.  Only an expression of my frustration in regard to the general Thunderbird-Exchange situation (which I completely blame Microsoft for) :-)
