### ISSUE TITLE
Feature Request: Support for TB 2021/78+ (current 85-beta3 and newer)

### ISSUE THREAD

**Issue by rlalik** [jobisoft/EAS-4-TbSync#140]
Hi,

would be great to have also support for new TB releases as I am fan of it (work pretty nice) and actually downgrading back to 78 makes TB working bad (I guess some files were converted and old TB has problem with it).

How can we help with migration? I was looking for some guides how to migrate to new TBs abut there is no many info here:

https://developer.thunderbird.net/add-ons/updating

I have also no experience with writing addons for TB but I learn quick ;-)

**Comment by jobisoft** [comment]
In my day job as Thunderbirds add-on support engineer I am currently mostly concentrating on fixing bugs in our APIs and helping add-on developers to write/update WebExtensions for TB78. I have currenlty not much time to work on my own add-ons.

What you could do to support me, is to manually remove the max version setting in the manifest file of TbSync and just check what is not working and where it fails. Either report that on discuss.thunderbird.net and ask for help, or dive into the source yourself via searchfox.org.

I usually start to work on https://developer.thunderbird.net/add-ons/updating once beta has reached the next ESR (which I think is 88).

**Comment by rlalik** [comment]
I played with it a bit and made it working for 78+ (Tested with TB-85.b3).
If you are willing to make a branch for TB 78+, I can make pull request to it.

Please see:
https://github.com/rlalik/EAS-4-TbSync/tree/thunderbird_78+
https://github.com/rlalik/TbSync/tree/thunderbird_78+

Though, there is still an exception which I could not handle, but seems to be harmless as far as I tested.

> [Exception... "Failed to open input source 'chrome://eas4tbsync/content/timezonedata/Aliases.csv'"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://eas4tbsync/content/includes/tools.js :: fetchFile/< :: line 90"  data: yes] tools.js:90:21
>     fetchFile chrome://eas4tbsync/content/includes/tools.js:90
>     fetchFile chrome://eas4tbsync/content/includes/tools.js:81
>     load chrome://eas4tbsync/content/provider.js:87
>     InterpretGeneratorResume self-hosted:1483
>     AsyncFunctionNext self-hosted:689
>

**Comment by jobisoft** [comment]
Is that file missing? If not, this error is crucial as tbsync cannot map IANA timzone names to windows time zone names and will mess up timezone conversions.

**Comment by rlalik** [comment]
File is not missing but could not find why it is not working. I am working on Linux thus I do not know if there any effects to Windows.

**Comment by jobisoft** [comment]
It is not depending on the OS, but EAS which is a Microsoft protocol uses the windows / Microsoft timezone names. I will have a look.

Is the modified version also running in TB78? Or do we need to add version based handling (I do not want to maintain two versions).

**Comment by rlalik** [comment]
It actually works. I somehow though the changes are related to 78+ only, and are not present in the 78, but it works.

The exception above is not present in 78.
