### ISSUE TITLE
incorrect data shown in Address Book Contact Pane for many synced contacts

### ISSUE THREAD

**Issue by boldcompany** [jobisoft/EAS-4-TbSync#143]
TbSync version: 2.20
EAS-4-TbSync version: 1.20
Thunderbird version: 78.8.1

Yes, I have installed the latest available beta version from https://tbsync.jobisoft.de and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
When contacts are synced, the correct information for each contact will display in the Address Book.

## Actual behavior
When reviewing a list of contacts shown in the Address Book that are synchronized by EAS-4-TbSync, details shown in the Contact Pane are often incorrect. In particular, phone numbers from various contacts are shown in other contacts' view. 

For example, a phone number of (ZZZ) XYX-YXYX is shown under Fred Smith, which is his actual number. Pressing the arrow key to navigate down the contacts list, Jim Thompson and Michael Frank are both shown to also have the same phone number in the Contact Pane. In reality, these three contacts are unrelated and the phone number is only in Fred's contact. If the two other contacts are opened in an Edit Contact window, the phone number is not in those contacts. Yet, the Contact Pane continues to erroneously show the phone number for all three contacts.

The erroneous data shown for some contacts seems to be sourced from the "Other Fields (EAS)" portion of other contacts. For example,  (ZZZ) XYX-YXYX is seen as Fred Smith's "Work Alternative Phone" under the "Other Fields (EAS)" tab when editing his contact in an Edit Contact window. This number is not shown in any tab or field in Jim Thompson or Michael Frank's contacts in an Edit Contact window, yet it shows as a "Work Alternative Phone" for each of them when viewing their contacts in the Contact Pane.

## Steps to reproduce
1. Sync contacts with TbSync and EAS-4-TbSync.
2. Navigate down the contact list in the Address Book.
3. Observe that incorrect data such as phone numbers are displayed for various contacts in the list.
4. Open individual contacts in an Edit Contact window and observe that the erroneous data is not in the individual contacts.

**Comment by rin67630** [comment]
me too...

I made an initial sync with my outlook.com account.
The configuration process was a breeze, Wonderful!
The calender synchronized perfectly.
But the Cards werealmost all incorrect, 
Where ist the filed mapping determined and acn one influence it?
Thank you
Laszlo

**Comment by jobisoft** [comment]
With Thunderbird 102, I no longer manipulate the contact pane. Sorry that I was not able to fix it in TB91 or before. I close it, as the reported issue no longer applies to EAS v4.x
