### ISSUE TITLE
Server responds with HTTP 415

### ISSUE THREAD

**Issue by bertsky** [jobisoft/EAS-4-TbSync#146]
## Your environment

TbSync version: 1.14
EAS-4-TbSync version: 2.12
Thunderbird version: 68.8

- [ ] No, I have not tried the beta and am aware that 68.8 is considered EOL now. Please just give your advice / opinion on whether this kind of problem might be solvable (with a newer version) at all. (I don't want to get into the hassle of dropping my Enigmail and all just to find out the add-on does not support my server anyway.)

## Expected behavior

After connecting and authenticating to the Exchange server, start synchronization (I guess – I've never seen it work).

## Actual behavior

After connecting and authenticating to the Exchange server, I get a `communication error (HTTP status 415)`.

That's true for both choices for `ActiveSync version` I can make, v2.5 and v14.0.

If instead I choose `best`, then the error is different, stating that the server does not advertise its ActiveSync version.

Here's a debug log:

```
** Thu Mar 18 2021 21:09:06 GMT+0100 (Mitteleuropäische Normalzeit) **                                                                   
[setSyncState] : State: prepare.request.options, Account: test
                                                                     
** Thu Mar 18 2021 21:09:06 GMT+0100 (Mitteleuropäische Normalzeit) **                                                                   
[Sending] : OPTIONS https://webmail.slub-dresden.de/ews/exchange.asmx/Microsoft-Server-ActiveSync                                        
                                                                     
** Thu Mar 18 2021 21:09:06 GMT+0100 (Mitteleuropäische Normalzeit) **                                                                   
[setSyncState] : State: send.request.options, Account: test
                                                                     
** Thu Mar 18 2021 21:09:06 GMT+0100 (Mitteleuropäische Normalzeit) **
[setSyncState] : State: eval.request.options, Account: test          
** Thu Mar 18 2021 21:09:06 GMT+0100 (Mitteleuropäische Normalzeit) ** 
[EAS OPTIONS with response (status: 200)] :                          
responseText:                                                        
responseHeader(MS-ASProtocolVersions): null                          
responseHeader(MS-ASProtocolCommands): null                          

** Thu Mar 18 2021 21:09:06 GMT+0100 (Mitteleuropäische Normalzeit) ** 
[EventLog] : InvalidServerOptions                                    

** Thu Mar 18 2021 21:09:06 GMT+0100 (Mitteleuropäische Normalzeit) ** 
[EventLog] : InvalidServerOptions                                    

** Thu Mar 18 2021 21:09:06 GMT+0100 (Mitteleuropäische Normalzeit) ** 
[setSyncState] : State: accountdone, Account: test
```

## Steps to reproduce

Add account, enter details, try connecting / start syncing – get error message.

**Comment by jobisoft** [comment]
That is not an EAS endpoint:
[Sending] : OPTIONS https://webmail.slub-dresden.de/**ews**/exchange.asmx/Microsoft-Server-ActiveSync     

Ask your IT for the EAS endpoint, if they have one. Or use the owl add-on, which is doing EWS sync.

**Comment by bertsky** [comment]
@jobisoft yes, absolutely, thanks a lot for pointing that out! I _did_ get it working with the right URL path on the old version. Awesome!
