### ISSUE TITLE
 Calendars keep disappearing due to invalid synchronization key (status 3)

### ISSUE THREAD

**Issue by jpennekamp** [jobisoft/EAS-4-TbSync#147]
## Your environment

TbSync version: 2.21
EAS-4-TbSync version: 1.20
Thunderbird version: 78.8.1 (64-bit)

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Calendars and contacts keep getting synchronized and they are not removed (by TBSync).

## Actual behavior
After a while for a (random?) subset of my five subscribed accounts, the calendars (and contacts) are removed and not shown anymore in TB. They are also not listed as available resources in the TBSync options anymore.
My main account (the one with the contacts) is always affected. The remaining accounts do not show a consistent pattern (alternating between all situations from zero to all being affected). 

I only synchronize the contacts for one account and do not synchronize tasks for any of them. Most likely, the issue is not linked to the exact resource though. Not synchronized resources remain in the list of available resources even when resources are "missing".

### Event log
Afterward, the event log always contains two entries for each account where the calendars are gone.
1. Forced Folder Resync (showing both the request and the response with status 3)
2. Invalid synchronization key (status 3), resyncing

Sometime a third entry follows: "There was an error from which we could not recover by resyncing the account. Please disable the account and try again. (Error: resync loop)"

### Resolving the situation
As stated in the third entry, disabling and enabling the account under general bring back all resources (including the resources that went missing). Afterward, the synchronization for the resource must be enabled again.
The tiresome part of this mitigation is that the colors must be changed (the configured and offered account colors are just hideous...) and that the main account must be manually linked to my email address.

## Steps to reproduce
Unclear. It might be an issue with the used exchange server. However, other colleagues with the same setup have no issue (a subset of the synchronized accounts is even identical).
I only recently updated from the latest TB 60 version and the exchangecalendar addon, which worked mostly flawless (occasionally the calendars were locked for brief moments until the next synchronization took place).

The described issue here seems to not appear with a fixed pattern. Sometimes, it works for 3-5 days, sometimes just a single one. I can observe the problem both on my MacOS device (which is usually hibernated with TB running) and Windows (where TB is only periodically opened).

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

Due to the inconsistent occurrence, the debug log is quite long. I am also providing a second one, which also includes the described steps to resolve the situation.

Thank you for your work and any support that you can give. Appreciate it.

**Comment by jobisoft** [comment]
Are you using TbSync on two (or more) Thunderbird instances and have you cloned the profile in those? That would mean both use the same "random" ClientID, which is not so random if cloned.

**Comment by jpennekamp** [comment]
Yes, the profiles were copied but I had to manually add the accounts in TBSync again (on the 2nd device).
Copying the profile was never an issue in the past.

**Comment by jobisoft** [comment]
Still, please remove all TbSync accounts from all instances and start from scratch (disable is not enough). I have no other idea.

**Comment by jpennekamp** [comment]
Okay, thanks!
