### ISSUE TITLE
Feature: Syncing multiple (shared) calendars

### ISSUE THREAD

**Issue by felfert** [jobisoft/EAS-4-TbSync#149]
I would love to see this feature implemented:
In the Exchange Web-Frontend, multiple shared calendars can be shown, if those are added to an accounts "Favorites".

Perhaps I could even implement that myself and create a PR if I would get some guidance about what to do protocol-wise.
I have some minor experience in writing FF addons.

Cheers
 -Fritz

**Comment by jobisoft** [comment]
If a calendar is announced via EAS, TbSync can see it already. But EAS does not announce shared calendars. If you want to see those, you got to use EWS (owl add-on).

**Comment by felfert** [comment]
Hmm. The OWA variant was just an example, so what about manually adding calendar-urls?

**Comment by jobisoft** [comment]
Not supported by EAS, it is based on IDs, not URLs.

**Comment by felfert** [comment]
Ok, so maybe we are doing something profoundly wrong in the first place.
You say: **If** a calendar is announced via EAS, TbSync can see it already.
So how does one get EAS to announce some Calendar publicly (writeable for some guy using Outlook, readonly for everyone else)?

Sorry for my naive questions (absolute noob regarding ActiveSync) - we had imap/caldav/carddav before and everything worked nicely - now some dumbass decided to migrate to EAS without asking us Linuxers and now all those problems pop up :-(

**Comment by jobisoft** [comment]
> So how does one get EAS to announce some Calendar publicly (writeable for some guy using Outlook, readonly for everyone else)?

Not possible. The EAS protocol does not support calendar sharing. It is the small brother of EWS, which does support all the heavy lifting.
