### ISSUE TITLE
TbSync.lightning.cal.createEvent is not a function

### ISSUE THREAD

**Issue by dewuer** [jobisoft/EAS-4-TbSync#151]
## Your environment

TbSync version: 3.00
EAS-4-TbSync version: 2.0
Thunderbird version: 91.0b5 (64 bits)

[x] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
...
Successful synchornization of calendar events.

## Actual behavior
...
![EAS error on calendar sync](https://user-images.githubusercontent.com/34125740/127823852-7fab7375-1f69-4a30-9d13-3866cf180671.png)

TbSync.lightning.cal.createEvent is not a function

createNewEvent@chrome://tbsync/content/modules/lightning.js:358:40
createItem@chrome://eas4tbsync/content/includes/sync.js:1105:40
processCommands@chrome://eas4tbsync/content/includes/sync.js:886:44

## Steps to reproduce
...
![eas sync](https://user-images.githubusercontent.com/34125740/127824223-081677d5-cdd8-456a-81b9-06b430ed4df2.png)

While everything is set pressing Synchronize now starts to sync Contacts (OK), but next step with syncing Events is ending with an error right at the beginning.

I know this is early stage of add-on development and also TB91 is still in beta, but Contacts are syncing without a single problem, but Events are not even starting to sync.

So far I am using TB 78.12.0 and older versions of TbSync and EAS-4-TbSync and everything is ok.
I was close to switch to TB 91 beta once I saw possibility to run add-ons, but problem with calendar events is only limiting to do so.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
That was fast. I uploaded the version for the EAS provider just a couple of hours ago! :-)

And you are correct. I only tested contacts. Thanks for reporting, I will have a look soon.

**Comment by jobisoft** [comment]
I have updated the master branches for TbSync and the EAS provider, which should fix the reported issue.

Can you confirm it is working now?

**Comment by dewuer** [comment]
TbSync version: 3.0**1**
EAS-4-TbSync version: 2.0.**1**
Thunderbird version: 91.0b**6** (64 bits)

Yes, right now it is working fine, Contacts and Events synchronized fine. Thank you.


![EAS ok on contact and calendar sync](https://user-images.githubusercontent.com/34125740/127965141-6d29aea8-f127-4c50-a761-9aea88acb4ea.png)
