### ISSUE TITLE
Calendar Event not Sync

### ISSUE THREAD

**Issue by felipetac** [jobisoft/EAS-4-TbSync#152]
## Your environment

TbSync version:2.22
EAS-4-TbSync version: 1.20
Thunderbird version: 78.13.0 (64-bit)

## Expected behavior
1. Add a event on thunderbird sync calendar
2. Enter on outlook 365 by browser
3. View the added event on thunderbird in outlook 365 website
...

## Actual behavior
1. Add a event on thunderbird sync calendar
2. Enter on outlook 365 by browser
3. Not view the added event on thunderbird in outlook 365 website
...

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Hit the sync button in the TbSync Manager or enable auto sync there. Also, please provide the version information at the top of this issue.

**Comment by felipetac** [comment]
Perfect! In my account was not setted the **period of sync (in minutes)**. I setted 1 minute and works! Thank @jobisoft! :)
