### ISSUE TITLE
Events not synchronised from server

### ISSUE THREAD

**Issue by lioneljm** [jobisoft/EAS-4-TbSync#154]
## Your environment

TbSync version:3.0.1
EAS-4-TbSync version:2.0.1
Thunderbird version:91.3.1 (64 bit)

## Expected behavior
...If an event is created on another device (e.g. Android) and synced to Outlook.com it should then sync to TB calendar

## Actual behavior
...Events created on another device do not sync to TB unless TBsync is set to 'Read-only server access'

## Steps to reproduce
...As above:
Create event on and Android calendar
Sync to Outlook.copm calendar
In TBsync click 'Synchronize now'

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by StianOby** [comment]
Could you try the "hide/unhide" workaround described in #153? I suspect this is a duplicate of #153

**Comment by lioneljm** [comment]
Thank you! The work-around does indeed work. It looks like the same issue, this time on Windows 10 (#153 was Mac OS).
