### ISSUE TITLE
Calendar does not sync on Microsoft 365 account (Communication error)

### ISSUE THREAD

**Issue by seboss666** [jobisoft/EAS-4-TbSync#157]
## Your environment

TbSync version: 3.0.1
EAS-4-TbSync version: 2.0.1
Thunderbird version: 91.3.2

## Expected behavior
Normal calendar synchronization. I already have some trouble with 78+ extensions as some locally created events break synchronization and needs to be manually removed (meeting approval for example that creates meetings copies in the calendar), but overall, it's working fine for the daily business.

## Actual behavior
Since tuesday morning, without any updates on my side (working on Manjaro), the calendar does not sync anymore. I cleaned some local errors mentioned above, but connection still failed after waiting some time. The error shows a 503 error from Microsoft, but no other details about the message.

## Steps to reproduce
[tbsync_debug.log](https://github.com/jobisoft/EAS-4-TbSync/files/7632795/tbsync_debug.log)

**Comment by jobisoft** [comment]
503 is a network error, maybe a downtime of the server?

**Comment by seboss666** [comment]
I can't even know, I don't seem to find a status page that should show something is not correct. 503 seems to be the way microsoft reports that we don't use the service correctly (seriously), But I have no details about requests sent or received (parameters, payload, etc).

Parallel to this specific problem, I also had some problems to contact IMAP, but that was resolved since. Not sure if there is something related.

**Comment by jobisoft** [comment]
If you enable debug logging in TbSync (Manager -> Help) You can see the full data exchanged.

**Comment by seboss666** [comment]
The log provided is with full logging enabled. I don't have an answer yet for a potential configuration change from my organization.

**Comment by seboss666** [comment]
Quick update : I'm working from home today, and everything is working fine (apart the already mentionend glitches I encounter sometimes that should rely in a dedicated issue). I plan to go back to office next week, I propose to keep this open until then (quite sure it will be monday), just to confirm if this could be a network related issue with my company.

**Comment by seboss666** [comment]
OK, I'm at the office this morning, and everything works as expected. As we had no status from infra team nor Microsoft (for them everything was fine), I really don't know where the truth is.
