### ISSUE TITLE
sometimes calendar sync ends with the "synchronization deactivation" of the account

### ISSUE THREAD

**Issue by ghost-from-the-past** [jobisoft/EAS-4-TbSync#158]
## Your environment
I use TB on Ubuntu 21.10 and on MacOS 12.0.1 (happens in both)

TbSync version:3.0.1
EAS-4-TbSync version:2.0.1
Thunderbird version: 91.3.2

I don't know what causes it.
I access/update my calendar from several different machines, OSs and Apps (web server, TB, MS Outlook)
On the client machines I only synch my calendar, not sync of task nor contacts.
I didn't set the periodic timer to re-sync (it is at 0). I do it manually going to TBSync and push the button "Sync now"

Sometimes when I sync TBSync shows a message about the account (sorry I'll pay more attention next time to take a screenshot of the text) and the available resources disappears.
I'm forced to untick "activate and sync this account"
tick it again
now the resources appears again
tick "calendar"
and push "sync now"
this time it takes the full calendar and works

the attached files are : 
log1 : from start until the resources disappeared (I went to the help tab, view the log and save it)
log2 : is the full up to then end, log1 and the continuation, re-activation and re-sync

happens more often when I sync from a machine that I not used during several days so seems to be related to the delta changes
As I don't know what is the cause so I can't repeat the error on demand.
If you found some clues in the log I'll be happy to help following your instructions to do tests and isolate the problem

Regards

**Comment by jobisoft** [comment]
Did you clone those profiles with active tbsync configuration, so all use the same deviceID (which is generated on account creation)? This can mess up the sync state.

**Comment by ghost-from-the-past** [comment]
I just read the issue https://github.com/jobisoft/EAS-4-TbSync/issues/147 (sorry it was in the closed list, this is why I didn't saw it before)
my TB profiles are cloned in all my machines...
Where is located the  "random" ClientID ? (to check in all my machines)
I'll change that setting to be unique in each one and see what happens.

Could you explain me a bit the problem ? the server send the deltas based in the ClientID ? and this breaks the consistency when using the same ClientID in different machines

**Comment by jobisoft** [comment]
> I just read the issue #147 (sorry it was in the closed list, this is why I didn't saw it before)

np

> Where is located the "random" ClientID ? (to check in all my machines)

![image](https://user-images.githubusercontent.com/5830621/146350592-1d4a0646-8ba6-4557-9e2c-45a97f98a613.png)

> Could you explain me a bit the problem ? the server send the deltas based in the ClientID ? and this breaks the consistency when using the same ClientID in different machines

Yes

>  I'll change that setting to be unique in each one and see what happens.

You will have to remove the tbsync account and set it up anew. DeviceID cannot be changed manually.

**Comment by ghost-from-the-past** [comment]
>You will have to remove the tbsync account and set it up anew.
>DeviceID cannot be changed manually.

ouchhh what a pain ...
is not in text accessible to root ? is encrypted in some db ?

thanks for all your help :)

**Comment by jobisoft** [comment]
With the autodetection mechanism of TbSync, it should not take you longer than 2 minutes. 

I strongly do not recommend to temper with internal files/DB of TbSync if you want to have a clean sync state at some point :-)

**Comment by ghost-from-the-past** [comment]
done, I have a new Active Sync ID now, thanks again.

Could you give access to the wiki ? or to a page in the wiki ? to document this setup and alert persons like me that clone their profiles

**Comment by jobisoft** [comment]
Wiki is open now, tell me when you are done, so I can lock it again. Thanks for your offer to help!

**Comment by ghost-from-the-past** [comment]
done
https://github.com/jobisoft/EAS-4-TbSync/wiki/General-troubleshooting
feel free to modify

**Comment by jobisoft** [comment]
thanks
