### ISSUE TITLE
outlook.com calendars not fetching with Javascript error in current beta - change in TB?

### ISSUE THREAD

**Issue by DavidBE-UK** [jobisoft/EAS-4-TbSync#159]
I rather suspect that a TB change in the beta is causing this, so this is a heads up before the change reaches the public channel - though it might be a bug in the beta instead I suppose. I THINK it started after updating the beta to 96.0b1, but I didn't notice the TbSync: Error message for awhile so I'm not sure if it actually started straight after the update.

## Your environment

TbSync version: 3.01
EAS-4-TbSync version: 2.01
Thunderbird version: 96.0b1 when it started. now 96.0b2

## Expected behavior
... The calendars my outlook.com account is subscribed to should continue syncing with TB as before.

## Actual behavior
... Initially, when I finally noticed, the calendars provided by outlook.com itself - my main Outlook calendar, the Birthday calendar and the United Kingdom Holidays calendar - continued syncing as before, but 3 WebCal.guru calendars, my Google calendar and one other external calendar my outlook.com calendar account is also subscribed to all failed to sync with TB via TbSync with the same error. After disabling and then re-enabling the account in TbSync ALL calendars fail, including the outlook.com own ones. They also all fail to sync after deleting then re-creating the account. (Address book/contacts still successfelly syncs.).

In the Event log, each failing calendar shows the same error message:

item is null

getItem@chrome://tbsync/content/modules/lightning.js:412:11

## Steps to reproduce
... As far as I know, using TbSync and EAS-4-TbSync and with an outlook.com account with subscribed calendars, update to the TB beta and then trigger a sync for the error to appear for external calendars the outlook.com account is subscribed to, and either disable then re-enable the account in TbSync or delete then recreate it for the error to also affect outlook.com 'native' calendars.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
https://github.com/jobisoft/EAS-4-TbSync/issues/167#issuecomment-1249030422
