### ISSUE TITLE
Unable to connect to Outlook.com account: 404 error

### ISSUE THREAD

**Issue by gbakeman** [jobisoft/EAS-4-TbSync#160]
## Your environment

TbSync version: 3.0.1
EAS-4-TbSync version: 2.0.1
Thunderbird version: 91.4.1

## Expected behavior
Account creation wizard completes successfully.

## Actual behavior
Account creation wizard reports a 404 error, nothing in the event log.

## Steps to reproduce
1. Create new Exchange ActiveSync account connection
2. Select Microsoft Office 365, enter account details
3. Click Autodiscover settings and add account

## Debug log
There isn't much to add here, only one line is available when logging all data transferred:

```
** Tue Jan 04 2022 16:23:25 GMT-0800 (Pacific Standard Time) **
[Querry EAS autodiscover V2 URL] : https://autodiscover-s.outlook.com/autodiscover/autodiscover.json?Email=(my email)&Protocol=ActiveSync
```

**Comment by jobisoft** [comment]
You can manually check the return value of that URL. If it is 404, your email is not usable with the O365 setup option.

**Comment by gbakeman** [comment]
Here is the raw data:

`{"Protocol":"ActiveSync","Url":"https://eas.outlook.com/Microsoft-Server-ActiveSync"}`

Request data:

```
Cache-Control: private
Content-Encoding: gzip
Content-Length: 187
Content-Type: application/json; charset=utf-8
Date: Wed, 05 Jan 2022 21:14:52 GMT
Server: Microsoft-IIS/10.0
Vary: Accept-Encoding
X-AspNet-Version: 4.0.30319
X-BEServer: MW4PR17MB4513
X-BackEndHttpStatus: 200
X-CalculatedBETarget: MW4PR17MB4513.namprd17.prod.outlook.com
X-DiagInfo: MW4PR17MB4513
X-FEServer: MWHPR02CA0004
X-FirstHopCafeEFZ: EAT
X-Powered-By: ASP.NET
X-Proxy-BackendServerStatus: 200
X-Proxy-RoutingCorrectness: 1
X-RUM-Validated: 1
request-id: 1b9eb223-ad68-69b9-234a-6b85579a9e47

Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.5
Connection: keep-alive
DNT: 1
Host: autodiscover-s.outlook.com
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0

```

I'm not sure how the plugin is getting a 404 error out of this.

**Comment by Kage-Yami** [comment]
I'm getting the same results; I select the Microsoft 365 option, put in a name and my email address, and get a 404 "returned". Checking the debug logs and calling the autodiscover API from the URL logged manually, gives me the same 200 OK result as above; no 404 to be seen.

My account has MFA enabled, and is in the `@outlook.com.au` domain. 

Thunderbird: 91.9.1 (64-bit)
TbSync: 3.0.2
Provider for Exchange ActiveSync: 2.0.1

**Comment by jobisoft** [comment]
Is someone able to provide a fix? I cannot reproduce that here.

**Comment by euandeas** [comment]
Im getting the same results aswell, any updates on possible fix?

**Comment by jaorueta** [comment]
Fails when `https://autodiscover-s.outlook.com/autodiscover/autodiscover.json` responses 
`{"Protocol":"ActiveSync","Url":"https://eas.outlook.com/Microsoft-Server-ActiveSync"}`

`getOAuthObj` only supports the host `outlook.office365.com`

**Comment by jobisoft** [comment]
Interesting. Can you turn this into a PR?
