### ISSUE TITLE
Please tag version 2.x

### ISSUE THREAD

**Issue by Mechtilde** [jobisoft/EAS-4-TbSync#166]
## Your environment

TbSync version:
EAS-4-TbSync version:
Thunderbird version:

## Expected behavior
...

## Actual behavior
...

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Done.
