### ISSUE TITLE
How to check that GAL lookup is working?

### ISSUE THREAD

**Issue by lockywolf** [jobisoft/EAS-4-TbSync#175]
## Your environment

TbSync version: 3.0.2
Thunderbird version: 91.8.0

## Expected behavior
Typing people's names in the top-right search bar while the EAS address book is selected should return a list of people in the GAL.

## Actual behavior
Nothing happens.

## Steps to reproduce
I don't know how to configure TbSync to search GAL. Does it work, or does it not? I have the "include results from global address book (GAL)" checkmark selected.

Debugging log does not seem to have anything suspicious. Is GAL misconfigured on the server?

**Comment by jobisoft** [comment]
GAL lookup has been removed temporarily in EAS v4.x and will be re-implemented differently. It will appear as an LDAP style address book, which will make it very easy to see whether GAL is working or not.

**Comment by bermeitinger-b** [comment]
Do you have a timeline or a priority setup for this feature? Is it going to take weeks, months, or years? I'd need to adjust or keep the current setup at the moment.
