### ISSUE TITLE
TBSync periodically creates `Local Backup of: X` calendars, removing old calendar settings

### ISSUE THREAD

**Issue by jobisoft** [jobisoft/EAS-4-TbSync#18]
_From @venthur on October 1, 2018 6:41_

## Your environment

TbSync version: 0.7.15
Thunderbird version: 60

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior

Leave my calendars alone

## Actual behavior

Every week or so my TBSync'd calendars have different settings (i.e. the color setting) and new calendars appear: `Local Backup of: $Calendar`

## Steps to reproduce

Setup a calendar with TBSync and wait for a few weeks.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

_Copied from original issue: jobisoft/TbSync#130_

**Comment by jobisoft** [comment]
Something is wrong, TbSync looses contact to the original caledar on the server. It will download the "new" calendar abd backup any old local "leftover" calendar.

What server are you connecting to? Horde?

**Comment by jobisoft** [comment]
_From @venthur on October 1, 2018 7:17_

It is an official microsoft server: https://outlook.office365.com

**Comment by jobisoft** [comment]
OK, then please update to the lastest stable an observe, if behavior changes. Version 0.7.16 fixes an exchange bug. Maybe it is related.

**Comment by jobisoft** [comment]
status?

**Comment by jobisoft** [comment]
_From @BillBrowne on October 7, 2018 21:30_

This has happened to me occasionally in the past and happened to me today. I was on the last debug release but just updated to 0.7.16.3 so am not sure what release I was on when it happened.

**Comment by jobisoft** [comment]
For every reporter in this issue: I need the following information per incident:
 - what type of server is that account connecting to
 - the additional info in the name of the backuped calendar/addressbook (for example "forced resync")

**Comment by jobisoft** [comment]
_From @BillBrowne on October 7, 2018 22:43_

The server I'm connected to is outlook.office365.com
Sorry, I deleted the back ups so cannot remember their names

**Comment by jobisoft** [comment]
_From @pcause on October 16, 2018 15:11_

I've had this as well.  I am on latest released (7.16).  The name of my backup was 

Local backup of: O365 Contacts [deleted from server] (*)

I am on a laptop, travel frequently and often get slow/intermittent connections to o365.  it's imap support is slow/bad.

**Comment by jobisoft** [comment]
@pcause when that happens, did ALL your folders (address books and calendars and tasks) pop off like that, or just some?

**Comment by jobisoft** [comment]
_From @pcause on October 16, 2018 16:20_

just my o365 address book,

**Comment by jobisoft** [comment]
This is important, so let me rephrase that: Did all folders you subscribed to using the tbsync manager pop off at the same time, or just one and the others remained?

**Comment by jobisoft** [comment]
_From @pcause on October 16, 2018 16:59_

Ok, not 100% sure what you are asking.  I have only one o365 account.  My calendar seemed to still be there/fine and I don't use tasks in o365.  mail folders (imap) all seemed fine

**Comment by jobisoft** [comment]
![image](https://user-images.githubusercontent.com/5830621/47033788-ff55ec00-d175-11e8-9fc9-47b648ce0d38.png)
As you can see, I have two folders subscribed. I do not know how many you have subscribed. I am asking, if this issue happens to all your subscribed folders at once, or if only one gets popped off (with a backup)

**Comment by jobisoft** [comment]
_From @pcause on October 17, 2018 1:47_

I have Contacts, Calendar and Tasks subscribed.

**Comment by jobisoft** [comment]
Thanks for your feedback. Could you check in lightning, if your calendar and task folder have also been backuped with [deleted on server]?

**Comment by jobisoft** [comment]
@pcause
@BillBrowne
@venthur

I would like to get this fixed before releasing the next version. Can you switch to beta and observe this issue? I was not yet able to reproduce that, but i made some changes, which could help.

The relevant information I need:
- what type of server is that account connecting to
- the additional info in the name of the backuped calendar/addressbook (for example "forced resync")

Instructions for switching to the new beta can be found here:
https://tbsync.jobisoft.de

**Comment by jobisoft** [comment]
This has been fixed now in the latest beta.

**Comment by lem503** [comment]
Hi, I am also having this issue on the latest beta with a calendar on outlook.office365.com syncing one calendar (out of several in that account) and contacts.

Using:
TbSync [Beta Release Channel] 1.7.6
Provider for Exchange ActiveSync [Beta Release Channel] 0.12.7

The calendars being created have the following naming scheme:
`Local backup of calendar_name [forced folder resync]`
The address books basically are the same:
`Local backup of calendar_name (Contacts) [forced folder resync]`

I am getting about 10-20 a day each.

The error log shows:
```
Forced Account Resync
Settings.110
```

Hope this helps.
