### ISSUE TITLE
'Local backup of: <calendar> [forced folder resync]' after sync

### ISSUE THREAD

**Issue by jobisoft** [jobisoft/EAS-4-TbSync#19]
_From @paul70078 on October 29, 2018 13:26_

When 2 Thunderbird instances sync the same calendar, backups of the calendar are created. Additionally event notifications pop up and need to be confirmed again.

## Your environment

TbSync version: v0.7.16
Thunderbird version: 60.2.1

[X] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior

No duplicate/backup calendars on sync

## Actual behavior

Local backup of <calendar> after sync

## Steps to reproduce

Adding the same calendar to 2 Thunderbird instances running at the same time

_Copied from original issue: jobisoft/TbSync#162_

**Comment by jobisoft** [comment]
What provider? EAS or DAV?

**Comment by jobisoft** [comment]
_From @paul70078 on November 5, 2018 11:11_

EAS according to log

**Comment by jobisoft** [comment]
@paul70078

I fail to reproduce this, at least with the latest beta. But I did not do any work dedicated to this issue, but maybe I fixed it by chance?

I setup an Office 365 account twice within the same Thunderbird instance and I can see how the changes done in one calendar propagate to the other (as expected). I do not see calendars being backuped.

Can you switch to beta and report back? In case you still observe that behavior, what kind of server are you connecting to?

Instructions for switching to beta:
https://tbsync.jobisoft.de

**Comment by paul70078** [comment]
@jobisoft 

Thanks for the update :) It seems to be working now.

If you encounter anyone else who got stack with too much calendar copys to be removed by hand (you can't remove multiple calendars at once), I would recommand to edit the prefs.js file in the Thunderbird profile folder. I had to remove ~800 duplicates.

**Comment by jobisoft** [comment]
You are on beta now? If you find anything strange in the beta, please report back. 

Thanks for the hint with the prefs.js!
