### ISSUE TITLE
Critical : Update to TB 102.2.2

### ISSUE THREAD

**Issue by gunter423** [jobisoft/EAS-4-TbSync#198]
Hi,

I open simple issue for know when tbsync and activesync as available to latest version of ThunerBird

![image](https://user-images.githubusercontent.com/24797165/195031486-63fa8250-9606-4aac-8f5d-c8917c35b819.png)

Have a nice day :)

**Comment by jobisoft** [comment]
https://github.com/jobisoft/EAS-4-TbSync/issues/167
