### ISSUE TITLE
suddenly stopped working - credentials invalid (?)

### ISSUE THREAD

**Issue by black-snow** [jobisoft/EAS-4-TbSync#199]
## Your environment

TbSync version: 4.3
EAS-4-TbSync version: 4.1.5
Thunderbird version: 102.4.0 (64-bit)

## Expected behavior

TbSync synchronizes stuff as usual.

## Actual behavior

TbSync cannot authenticate against M$.

![grafik](https://user-images.githubusercontent.com/579733/197147273-317de56f-e70d-4782-a100-46de8cc431aa.png)

![grafik](https://user-images.githubusercontent.com/579733/197147400-720271c1-f6bd-41ee-b9d7-373e1523316f.png)

## Steps to reproduce

Sadly, I don't know. My company has 2FA enabled but that wasn't an issue until now. I've heard that M$ changed something regarding "old login methods" but I haven't found anything regarding this yet.

I ain't got no admin privileges for MS365 so I cannot check the settings there atm.

> To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

```
** Fri Oct 21 2022 10:15:33 GMT+0200 (Mitteleuropäische Sommerzeit) **
[setSyncState] : State: prepare.request.options, Account: xxx

** Fri Oct 21 2022 10:15:33 GMT+0200 (Mitteleuropäische Sommerzeit) **
[Sending] : OPTIONS https://outlook.office365.com/Microsoft-Server-ActiveSync

** Fri Oct 21 2022 10:15:33 GMT+0200 (Mitteleuropäische Sommerzeit) **
[setSyncState] : State: send.request.options, Account: xxx

** Fri Oct 21 2022 10:15:33 GMT+0200 (Mitteleuropäische Sommerzeit) **
[setSyncState] : State: eval.request.options, Account: xxx

** Fri Oct 21 2022 10:15:33 GMT+0200 (Mitteleuropäische Sommerzeit) **
[setSyncState] : State: passwordprompt, Account: xxx

** Fri Oct 21 2022 10:15:38 GMT+0200 (Mitteleuropäische Sommerzeit) **
[setSyncState] : State: send.request.options, Account: xxx

** Fri Oct 21 2022 10:15:38 GMT+0200 (Mitteleuropäische Sommerzeit) **
[setSyncState] : State: eval.request.options, Account: xxx

** Fri Oct 21 2022 10:15:38 GMT+0200 (Mitteleuropäische Sommerzeit) **
[setSyncState] : State: passwordprompt, Account: xxx

** Fri Oct 21 2022 10:15:39 GMT+0200 (Mitteleuropäische Sommerzeit) **
[EventLog] : 401


** Fri Oct 21 2022 10:15:39 GMT+0200 (Mitteleuropäische Sommerzeit) **
[EventLog] : 401


** Fri Oct 21 2022 10:15:39 GMT+0200 (Mitteleuropäische Sommerzeit) **
[setSyncState] : State: accountdone, Account: xxx
```

**Comment by black-snow** [comment]
P.S.: Also lost access to a shared email account at the same time - probably due to the same issue.

**Comment by jobisoft** [comment]
Re-Setup your TbSync account (remove + new) with O365 setup option (the 3rd one).

**Comment by wwolfi** [comment]
I have the same issue, without 2FA account. I have the same environment:  
TbSync version: 4.3
EAS-4-TbSync version: 4.1.5
Thunderbird version: 102.4.0 (64-bit)
Removing the account didn't solve the issue.  Still HTTP Error 401.

**Comment by black-snow** [comment]
Thanks for the quick reply.

![grafik](https://user-images.githubusercontent.com/579733/197477748-0e6d8627-e9fc-4582-ba71-09dcb63c8b73.png)

Why does it need admin approval?

**Comment by jobisoft** [comment]
Because your IT department does not allow 3rd party apps and requests whitelisting.

**Comment by black-snow** [comment]
Aight, thanks. Will reopen in case anything else comes up :)
