### ISSUE TITLE
Make client UUID configurable

### ISSUE THREAD

**Issue by jan-kiszka** [jobisoft/EAS-4-TbSync#200]
We already have config vars for customizing device type and user agent strings, and I used them successfully in the past. Would you accept a PR that also makes client_id used for OAuth customizable? `extensions.tbsync.eas.clientID.uuid` or so. That can help to make things work again in certain environments if you know a permitted ID.

**Comment by jobisoft** [comment]
You sure you want to do that? Client IDs are used to track sync states. You will mess up your sync state and cause endless sync loops, if you use the same clientID in more than one installation/device.

**Comment by jobisoft** [comment]
And where is that used in TbSync?

**Comment by jan-kiszka** [comment]
https://github.com/jobisoft/EAS-4-TbSync/blob/70f288f0098b710beb3c8a5f3aa8652b229a76a1/content/includes/network.js#L88

**Comment by jobisoft** [comment]
Oh, that! Sure. Go ahead.

**Comment by jobisoft** [comment]
The name of the pref should include OAUTH. How about `extensions.tbsync.eas.oauth.clientID`?

**Comment by jobisoft** [comment]
Since you work in that area, can you confirm (or not) this:
https://github.com/jobisoft/EAS-4-TbSync/issues/169

**Comment by jobisoft** [comment]
Merged it today, will push it soon. Thanks for your patience.
