### ISSUE TITLE
Events are grayed/dimmed

### ISSUE THREAD

**Issue by AGI-chandler** [jobisoft/EAS-4-TbSync#201]
## Your environment

TbSync version: 4.3
EAS-4-TbSync version: 4.1.5
Thunderbird version: 102.3.3

## Expected behavior
All events show up brightly

## Actual behavior
Some events are grayed/dimmed and I can't figure out why.  Is it a Tbsync issue or issue with the event itself?

## Steps to reproduce
Nothing out of the ordinary, add a new account and sync the calendar events.

## debug.log
Nothing interesting, everything loaded and initialized, just some infos that "IANA timezone {foo} cannot be mapped to any Exchange timezone"

**Comment by jobisoft** [comment]
Probably tentatively accepted or something.

**Comment by AGI-chandler** [comment]
Perhaps.  I see an event with status "Tentative" so I opened the event and accepted it.  Now when I reopen it it says I've "accepted this invitation" but down in the General info it still says "Status: Tentative"

**Comment by jobisoft** [comment]
In general, TbSync/EAS has no proper meeting accept/decline support. If you need that, you will have to switch to OWL.

**Comment by AGI-chandler** [comment]
Oh, that's kind of a problem then isn't it?  Will you be able to add support for that?  What's OWL?

**Comment by jobisoft** [comment]
https://addons.thunderbird.net/addon/owl-for-exchange/

They use the business protocols (EWS, OWA) and not the simple mobile EAS protocol to connect with Exchange. Ask their support if they support calendars (I think so, but am not sure). It is a paid add-on (TbSync/EAS is free and I am not able to add meeting support in the short term, maybe 2024)

**Comment by AGI-chandler** [comment]
Ok thanks... I tried it out and seems to be working, it comes with a free month and not very expensive either.  Although it adds a whole new email account too which is unnecessary, but maybe I can disable/hide it or should switch to using it that way.  Thanks for the recommendation!  guess I can close this now
