### ISSUE TITLE
Can't access Office365 directory

### ISSUE THREAD

**Issue by jethrogb** [jobisoft/EAS-4-TbSync#204]
TbSync version: 4.3
EAS-4-TbSync version: 4.1.5
Thunderbird version: 102.4.1

I used to be able to search the Office365 directory for contacts, when typing a name in the To-field when composing an email. This doesn't work anymore. I think it's TbSync that used to make this possible, but I'm not 100% sure? A lot of things changed recently - new TB, new authentication method, new TbSync, new EAS provider. [This page](http://kb.mit.edu/confluence/display/mitcontrib/Configure+Thunderbird+for+use+with+MIT+Exchange+or+MIT+Office365+Mailboxes) suggests it's done by TbSync/EAS.

**Comment by jobisoft** [comment]
Yep.
