### ISSUE TITLE
Release notes at about:addons

### ISSUE THREAD

**Issue by grahamperrin** [jobisoft/EAS-4-TbSync#205]
## Your environment

TbSync version: 4.3
EAS-4-TbSync version: 2.0.1
Thunderbird version: 102.4.0 (64-bit)

## Expected behavior

Release notes at about:addons and at <https://addons.thunderbird.net/en-GB/thunderbird/addon/eas-4-tbsync/versions/>

## Actual behavior

![image](https://user-images.githubusercontent.com/192271/198783346-2bb4e217-98af-4146-8658-4c487110cd9f.png)

## Steps to reproduce

At about:addons, click Release Notes. 

## Suggestion

Refer to: 

* https://github.com/jobisoft/EAS-4-TbSync/releases

Similarly, for <https://github.com/jobisoft/TbSync>, refer to: 

* https://github.com/jobisoft/TbSync/releases

**Comment by jobisoft** [comment]
FYI: There is a blue dot next to "..." button in your screenshot, which indicates you could update TbSync.

**Comment by grahamperrin** [comment]
Thanks, in Firefox and Thunderbird I always aim for release notes _before_ deciding whether to allow an update.

**Comment by grahamperrin** [comment]
I have Provider for Exchange ActiveSync `4.2`, which is not listed at https://github.com/jobisoft/EAS-4-TbSync/releases

I see that an update is available, but I can't guess the version, or what has changed.

**Comment by jobisoft** [comment]
I am sorry, I do not have time for this. I am actually happy I can get updates out at all.
