### ISSUE TITLE
No emails after update

### ISSUE THREAD

**Issue by dbfin** [jobisoft/EAS-4-TbSync#206]
TbSync version: 4.3
EAS-4-TbSync version: 4.1.5
Thunderbird version: 102.4.0

Had the same problem as in Issue #199, when suddenly Thunderbird started to ask for credentials. Removed and tried to add again the account using the third option, and it goes through except now when I click `Enable and synchronize this account` in the account manager dialog it lists a few calendars, tasks and contacts, but not emails, and when I go to the Inbox, there is no email account added. Used to work before, and I believe Thunderbird was recently updated to the version above. Any suggestions what to try?

**Comment by jobisoft** [comment]
Sorry, but TbSync never did emails.

**Comment by dbfin** [comment]
Okay, then probably I had it set up in a different way... I mean before I deleted the account. Somehow I was sure I had it set up via TbSync and its ActiveSync extension, and I do not have any other extensions installed, but maybe I did something in addition for emails (it was some time ago, like 2 years ago). In any case, please feel free to delete this issue if you are sure I did it in a different way. Now I just have to figure out how I did it or rather how to do it now, because the standard IMAP is not supported by the organization. Regardless, thanks for your work!

**Comment by jobisoft** [comment]
The only option I see for non-imap / exchange email accounts is OWL add-on or ExQuilla add-on.
https://addons.thunderbird.net/en-us/thunderbird/addon/owl-for-exchange/
https://addons.thunderbird.net/en-us/thunderbird/addon/exquilla-exchange-web-services/

If you have password issues with your TbSync account, you may need to delete it and set it up anew with the modern authentication option.

**Comment by dbfin** [comment]
Okay, thank you! I will try these options.
