### ISSUE TITLE
Not compatible with Thunderbird 102.2.2 

### ISSUE THREAD

**Issue by faxfax** [jobisoft/EAS-4-TbSync#207]
Hi everybody,

after my distributor upgraded to Thunderbird 102.2.2 (Linux Mint), i got an error message that Exchange cannot be started because it is not compatible with this version of Thunderbird.

Greetings from Italy,
Fabio

**Comment by jobisoft** [comment]
I delibratly do not allow TbSync to run with Thunderbird 102.2.* because it is old and broken (it has a data-loss bug in the address book component).

This has been fixed weeks ago and current TB is 102.4.1. I really have no idea why your distro is shipping such an old and broken version.
