### ISSUE TITLE
`invalid_scope` error after OAuth2 login

### ISSUE THREAD

**Issue by emericv** [jobisoft/EAS-4-TbSync#209]
## Your environment

TbSync version: 4.3
EAS-4-TbSync version: 4.1.5
Thunderbird version: 102.4.0

## Expected behavior
I cannot connect to my Office365 company account anymore since one week

## Actual behavior
After a login with OAuth2 there is the following error in the logs console :
> https://login.microsoftonline.com/common/oauth2/nativeclient?error=invalid_scope&error_description=The%20provided%20value%20for%20the%20input%20parameter%20%27scope%27%20is%20not%20valid.%20The%20scope%20%27offline_access%20https://outlook.office.com/.default%27%20is%20not%20valid%20-%20it%20refers%20to%20a%20resource%20which%20is%20not%20listed%20in%20the%20client%27s%20Required%20Resource%20Access%20and%20for%20which%20the%20user%20does%20not%20have%20any%20existing%20consent

Decoded error description in this URL:
> error: invalid_scope
> error_description: The provided value for the input parameter 'scope' is not valid. The scope 'offline_access https://outlook.office.com/.default' is not valid - it refers to a resource which is not listed in the client's Required Resource Access and for which the user does not have any existing consent

## Steps to reproduce
Login with a company account

PS: the `debug.log` is empty

**Comment by jobisoft** [comment]
Still valid with this version:
https://github.com/jobisoft/EAS-4-TbSync/issues/215#issuecomment-1416725608

?

**Comment by emericv** [comment]
> Still valid with this version: [#215 (comment)](https://github.com/jobisoft/EAS-4-TbSync/issues/215#issuecomment-1416725608)
> 
> ?

It seems to be OK with the last version!
Thanks for your support.
