### ISSUE TITLE
Issue lauching EAS + timezone problems 

### ISSUE THREAD

**Issue by johnjohnk2** [jobisoft/EAS-4-TbSync#214]
## Your environment

TbSync version: 4.3
EAS-4-TbSync version: 4.1.5
Thunderbird version: 102.6.1

Hi, I often face difficulties with EAS. Sometimes when lauching ThB, I have this message as if EAS plugin was not installed but it is, preventing any synchro operation 
![image](https://user-images.githubusercontent.com/36307676/209444398-28d1884e-470a-4c84-ae77-17fef0389d25.png)
And when EAS lauch effectively I often face difficulties with timezone. 
I don't know if timezone issue is TbSync or EAS issue , i found an old thread about it but it seems to closed 
Timezone-issue #187 -> https://github.com/jobisoft/TbSync/issues/187

Here is my log file 

[debug.log](https://github.com/jobisoft/EAS-4-TbSync/files/10298897/debug.log)

Thanks for your help

**Comment by johnjohnk2** [comment]
OK I solved some problems by downgrading ActiveSync version 
![image](https://user-images.githubusercontent.com/36307676/209479584-062337af-ec49-4ba8-9492-2dda314d143a.png)

**Comment by jobisoft** [comment]
This is a known issue, that TbSync sometimes fails to find EAS. Just disable and re-enable EAS add-on and it should work. Changing the protocol version might not be needed.
