### ISSUE TITLE
Can't authenticate to or create a Microsoft Office 365 account

### ISSUE THREAD

**Issue by dhwalker** [jobisoft/EAS-4-TbSync#219]
## Your environment

TbSync version: 4.3
EAS-4-TbSync version: 4.1.5
Thunderbird version: 102.7.1 (64-bit) (Linux)

## Expected behavior
...
Successful authentication and account creation.

## Actual behavior
...
For the past few days, I have not been able to synchronize my calendars, due to authentication errors. I tried removing the EAS-4-TbSync account and recreating it (Account actions -> Add new account -> Exchange ActiveSync -> Microsoft Office 365), and got:

    Server not found

    undefined could not be found. Please check the name and try again.

    Check the address for typing errors such as ww.example.com instead of www.example.com
    If you are unable to load any pages, check your computer's network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Thunderbird is permitted to  access the Web.

    Try again.

(Sorry about not capturing authentication error logs before deleting the account.)

## Steps to reproduce
...
Try to create a Microsoft Office 365 account.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
https://github.com/jobisoft/EAS-4-TbSync/issues/215#issuecomment-1416725608
