### ISSUE TITLE
choose between email address or username as login

### ISSUE THREAD

**Issue by bromix** [jobisoft/EAS-4-TbSync#22]
We've 2 accounts in our company. But for the login it's not the mail address, instead the username. Is there any way to say that I must use a username for the login. The second account don't uses the mail address.

This behavior is working with EWS-Provider, where I can choose between username and mail as login.

**Comment by bromix** [comment]
Okay...that's strange. I now my secondary username. With my first username it's working (also in EWS-Provider Addon). But I can't get it working with this awesome addon.
![image](https://user-images.githubusercontent.com/4136891/48361648-38647c00-e6a2-11e8-86dc-58459f245d3d.png)

**Comment by bromix** [comment]
Okay...just to let you know. Based on this issue (I now see) https://github.com/jobisoft/EAS-4-TbSync/issues/21 ... the problem seems to be the configuration on our site (EAS vs EWS). The second account is only working on EWS. Damn :) Keep up the good work.

**Comment by jobisoft** [comment]
So you have two accounts, one works and the other does not? 

Check with your IT if EAS is enabled for the second account as well.

**Comment by bromix** [comment]
Hi, we got it sorted out and you're right. It was EAS. Without your hint to check these settings we wouldn't have found it. The first account was working with EAS and EWS and second account only with EWS. That also reviled to us, that I could only login via owa.XXXXXX.com with the first account, but not with the second account. Now both accounts are configured correctly and are working with the addon. Thanks for the help.

**Comment by jobisoft** [comment]
You are welcome. Glad it works now.
