### ISSUE TITLE
Javascript Error: offset is outside the bound of the DataView

### ISSUE THREAD

**Issue by RadxaYuntian** [jobisoft/EAS-4-TbSync#221]
## Your environment

TbSync version: 4.3
EAS-4-TbSync version: 4.3
Thunderbird version: 102.9.0

## Expected behavior

EAS is able to fetch remote calendar.

## Actual behavior

EAS failed to parse the event.

## Steps to reproduce

Sync with my WeCom calendar:

![image](https://user-images.githubusercontent.com/95260730/226269728-b21af3c7-e0c3-41ea-a949-920434f75c55.png)

I do not create or edit event within Thunderbird, so they are entirely created on the remote server by Tencent's own code.

Full logs are sent in email.

**Comment by elcalvo75** [comment]
I have the same issue. Have you found a solution for this ?

**Comment by RadxaYuntian** [comment]
Nope and I simple gave up on event syncing with TbSync.

**Comment by jobisoft** [comment]
Unknown token 61 (0x3D) for codepage 18 indicates that this is not a proper EAS server or an EAS server with non-standard extension.

Contact your service provider.

**Comment by RadxaYuntian** [comment]
As expected, Tencent customer service is totally useless and does not understand what services they even provide.

I do not want TbSync to bend over to support their bullshit, so I'll close this for now.
