### ISSUE TITLE
Tag - Category Sync

### ISSUE THREAD

**Issue by scollovati** [jobisoft/EAS-4-TbSync#229]
Hi,
I know that currently Thunderbird does not sync Tags with Office365 mail categories. Do you think that this can be implemented via EAS?

**Comment by jobisoft** [comment]
I do not at all sync mails.

IIRC, I do sync contact categories (see https://addons.thunderbird.net/addon/categorymanager/, native support of Categories in Thunderbird address book is planned for 2024)

**Comment by scollovati** [comment]
Thanks for your suggestion. I was referring to mail tags, that are called categories in O365.

**Comment by scollovati** [comment]
@jobisoft could you please tell me where I can find documentation for this feature?
