### ISSUE TITLE
Reminders disappearing on some occurrences of recurring events

### ISSUE THREAD

**Issue by alistairlow** [jobisoft/EAS-4-TbSync#23]
## Your environment

TbSync version: 0.7.18
Thunderbird version: 60.3.1

[ x ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Once a reminder is set on an event, it continues to be set until it is unset (or maybe dismissed - I'm not sure what happens in that case).

## Actual behavior
Alarms for some occurrences of a recurring event are unset - this appears to be limited to occurrences that are changed in some way e.g. renamed, moved to another room, time changed etc.

## Steps to reproduce
* Create a weekly event in the Office 365 web application, with a reminder set.
* Synchronise your calendar in Thunderbird and observe that the weekly event appears, and the reminder is set.
* Edit the first occurrence of the event in the Office 365 web application, and change its name. Do not remove the reminder.
* Synchronise your calendar in Thunderbird again. The reminder will disappear from the first occurrence of the event.
* Edit the first occurrence of the event in the Office 365 web application. Observe that the reminder is still set.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
I transferred the issue to the new home of the EAS Provider: EAS-4-TbSync.

Due to technical reasons, I cannot work on this for about 2 weeks.

**Comment by jobisoft** [comment]
ChrisJAllan fixed this! Wanna give it a try?
https://github.com/jobisoft/TbSync/releases/download/v0.7.19/TbSync-0.7.20.xpi

**Comment by alistairlow** [comment]
Thanks! I try the steps above to reproduce the issue, and the bug wasn't present. Also disabled and re-enabled my calendar and all of my alarms reappeared. So, this fix looks good to me!

**Comment by jobisoft** [comment]
0.7.20 with this fix is out
