### ISSUE TITLE
Different calendars list from exchange on Linux and Windows

### ISSUE THREAD

**Issue by kartun83** [jobisoft/EAS-4-TbSync#232]
## Your environment

TbSync version:
EAS-4-TbSync version: 4.3
Thunderbird version: 102.13.1

## Expected behavior
...
Same list of calendars on linux and windows using exchange
## Actual behavior
...
On linux there main entry calendar is missing
## Steps to reproduce
...
IDK
To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
A debug log from both systems when the initial sync is performed might be helpful.
