### ISSUE TITLE
115 compatibility

### ISSUE THREAD

**Issue by Trapulo** [jobisoft/EAS-4-TbSync#233]
## Your environment

TbSync version:
EAS-4-TbSync version: 4.4
Thunderbird version: 115.0.1

## Expected behavior
It works

## Actual behavior
TB has disabled it reporting is not compatible with TD 115

## Steps to reproduce
Upgrade TB to 115

**Comment by UserX404** [comment]
https://github.com/jobisoft/EAS-4-TbSync/issues/220#issuecomment-1636741658

**Comment by myssv** [comment]
I can't add all my calenders, because there is no scroll bar and no OK button

![grafik](https://github.com/jobisoft/EAS-4-TbSync/assets/65643813/c1909cd3-8faa-48cf-8367-09f2bca24d80)

**Comment by PurpleZ2023** [comment]
and the arrow keys on the keyboard?

**Comment by myssv** [comment]
The cursor-line is moving out of the windows

![grafik](https://github.com/jobisoft/EAS-4-TbSync/assets/65643813/51b3b753-2130-40d8-8959-0f57f1a83d2d)

1 time arrow down

![grafik](https://github.com/jobisoft/EAS-4-TbSync/assets/65643813/399e7095-8e3e-44b0-b762-cbbca2e6ce7e)

2nd time arrow down

![grafik](https://github.com/jobisoft/EAS-4-TbSync/assets/65643813/ed5a8444-5f72-48ad-8ac8-db3d33b0a238)

**Comment by Trapulo** [comment]
> [EAS-4-TbSync115.1.zip](https://github.com/jobisoft/EAS-4-TbSync/files/12239050/EAS-4-TbSync115.1.zip)

Can someone post a compiled release?
thanks

**Comment by dicer** [comment]
Nothing to compile. Just execute the Makefile.bat (Windows with 7zip installed) or `make` (Linux). Alternatively have a look at the file and zip together the mentioned files/directories manually

**Comment by Trapulo** [comment]
@dicer I tried but loading the generated .xpi TB (Windows, 115.0.1) reports that "is not compatible" with that version :(

**Comment by pcause** [comment]
i did this and while it installs the Microsoft365 doesn't seem to work.  Can't get the Oauth stuff.

**Comment by jobisoft** [comment]
Compatible version has been submitted vor review. The scroll bar issue is a general TbSync issue and will be covered here:
https://github.com/jobisoft/TbSync/issues/683

**Comment by fdellwing** [comment]
Can you provide a handy .zip for quick update John?

TbSync autoupdated to 4.6 while EAS is still on 4.4 and is now throwing `OS is not defined` errors left and right.

**Comment by jobisoft** [comment]
I hope the pending provider releases are reviewed soon.

**Comment by Trapulo** [comment]
I've done same as @pcause and also my env is working now. Thanks
