### ISSUE TITLE
EAS4 4.5 is crashing Thunderbird 115 at sync of calendar

### ISSUE THREAD

**Issue by myssv** [jobisoft/EAS-4-TbSync#234]
## Your environment

TbSync version:
EAS-4-TbSync version: 4.5
Thunderbird version: 115.1.0 (64Bit)

## Expected behavior
normal syncing

## Actual behavior
sync fcrashed TB

## Steps to reproduce
Just start syncing the calendar

![grafik](https://github.com/jobisoft/EAS-4-TbSync/assets/65643813/99eb1ca0-7e8d-40d3-bd06-4faf31ae655c)

it starts

![grafik](https://github.com/jobisoft/EAS-4-TbSync/assets/65643813/46d7d6f5-8b32-4654-9f93-fe4dde8d8e21)

and then crash

![grafik](https://github.com/jobisoft/EAS-4-TbSync/assets/65643813/8a1aa315-5773-4de0-85d1-bca9395ceb61)

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

Mail is sent!

**Comment by myssv** [comment]
Syncing RSS calendar feeds is ok, but syncing my birthday calendar also crashes

![grafik](https://github.com/jobisoft/EAS-4-TbSync/assets/65643813/e2d24a7d-f16b-49ee-ac7b-698dfcab78dc)

**Comment by myssv** [comment]
is there anything I can do to help and fix the problem?

**Comment by jobisoft** [comment]
Yes, open the error console (press CTRL + SHIFT + J in the main TB window) and look at error messages which pop up when the syncing crashes.

**Comment by myssv** [comment]
![grafik](https://github.com/jobisoft/EAS-4-TbSync/assets/65643813/ecfb8292-0c4c-4f0a-8d66-77f4e063739a)

pressing Strg + Shift + j doesn't do anything ...

**Comment by jobisoft** [comment]
> (press CTRL + SHIFT + J in the **main TB window**)

**Comment by myssv** [comment]
ok, my fault .....

![grafik](https://github.com/jobisoft/EAS-4-TbSync/assets/65643813/1f60bc48-d85c-420b-8f1a-79df1ce170ca)

**Comment by jim-davenport** [comment]
I am having the exact same problem as well...

**Comment by jim-davenport** [comment]
I just posted in TBSync issues as I'm not sure which one is the cause. Where are we with this problem? I can downgrade to 102 if it's going to be a while. Please let me know. Thanks.

**Comment by myssv** [comment]
Wie kann ich Dir die Daten zukommen lassen?

**Comment by jobisoft** [comment]
Via email. It is listed here: https://github.com/jobisoft

**Comment by jim-davenport** [comment]
For me it is our personal O365 account. How do I send a calendar without giving my login information? (which is the key to my life.)


________________________________

Jim Davenport
Information Technology/Interactive Media

Bridgeport High School
55707 Industrial Drive
Bridgeport, OH 43912
740.635.0853 x6090

________________________________

**Comment by jobisoft** [comment]
You should be able to export it in the O365 web interface.

**Comment by jim-davenport** [comment]
I see where I can share, but not export. I'll keep looking. Anyone else know how to do this? Thanks!


________________________________

Jim Davenport
Information Technology/Interactive Media

Bridgeport High School
55707 Industrial Drive
Bridgeport, OH 43912
740.635.0853 x6090

________________________________

**Comment by jim-davenport** [comment]
Got it. I'll email the ICS file directly to you.


________________________________

Jim Davenport
Information Technology/Interactive Media

Bridgeport High School
55707 Industrial Drive
Bridgeport, OH 43912
740.635.0853 x6090

________________________________

**Comment by jobisoft** [comment]
We have to be more specific on the issue, as I think I see multiple fails here. 

The file I got from @myssv fails to be imported as an ICS file. I get

```
can't access property "toLowerCase", id is null when parsing
```

It can also not be synced via CardDAV (native Thunderbird) and apparently also not via EAS (TbSync). It causes Thunderbird to be non-responsive. There is no error printed to the console during CardDAV sync. I still have to check what happens during EAS sync.


The file I got from @jim-davenport can be imported, it prints

```
Could not find definition for Customized Time Zone
Could not find definition for Eastern Standard Time
```

I still have to check what happens during EAS sync.

**Comment by TBrianB** [comment]
I have this too. Calendar (outlook.com) freezes when synching at 78/114 ( it was 100/113 until a day or so back?) items.
At the same time duplicate calendars seem to get created
![eas3](https://github.com/jobisoft/EAS-4-TbSync/assets/143229939/d8d11736-5f90-4f46-9224-0fc6e29e006a)
![eas2](https://github.com/jobisoft/EAS-4-TbSync/assets/143229939/ff5bdf72-8e6e-4ce2-8cd6-7b39173aeec7)

**Comment by myssv** [comment]
For me it is working now!

Thanks a lot!!

**Comment by TBrianB** [comment]
I'm actually on the 4.7 version already. Is that zip file different to the one installed via the TB add-ons page?

**Comment by jobisoft** [comment]
That is a beta of TbSync, not the EAS provider. Official last version of TbSync is 4.6.

**Comment by TBrianB** [comment]
Sorry, misread it.

**Comment by TBrianB** [comment]
And, that just worked. Thanks.
If ever you have time could you point me (us) to an explanation of how the TNSync/EAS combination works, i.e what each does and how they fit together to make a single functionality. Please. I find it intruiging.

**Comment by jobisoft** [comment]
TbSync is a multiprotocol sync manager. For example there is also google-4-tbsync (not written by me). It was once intended as an open platform. My own two providers are DAV and EAS, which tell TbSync how to sync these protocols. DAV has become almost obsolete already.

**Comment by jobisoft** [comment]
This specific bug was in TbSync's calendar interface. TbSync provides a simplified API to add/remove/modify events in Thunderbird. I put that into TbSync, as I figured all providers need that functionality (but they also can use their own implementation). 

I derived that calendar interface from Thunderbird's own implementation back in 2014 (?) and there is a small chance, that core code also suffers now from the same issue, which could explain why the native Thunderbird CalDAV sync also triggers the freeze, as observed by @myssv .

**Comment by otristrichter** [comment]
Thanks very much John. The TbSync_beta_4_7.zip solved the hang using EAS to our Exchange 2019 server, too.

**Comment by Ule15** [comment]
With the beta I can sync all of my Calenders again. Thank you.

Greetings Uli Koetter

**Comment by jobisoft** [comment]
Released.
