### ISSUE TITLE
Outlook Group Calendar not visible

### ISSUE THREAD

**Issue by sridharraman** [jobisoft/EAS-4-TbSync#237]
## Your environment

TbSync version: 4.3
Thunderbird version: 102.13.0 (64-bit)

## Expected behavior
I have added an Outlook calendar from my organisation. I want to see the events from all my calendars (personal, holidays, tasks, etc.) as well as any Group calendars that I follow.

## Actual behavior
The individual calendars appear fine. But, none of the Group calendar events are seen. In fact, the Group calendar doesn't come up as an option in the sync window itself.

## Steps to reproduce
Synchronise an Outlook account that also follows a Group calendar. The main calendar comes fine, but the Group calendar won't.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

Any idea if this ever used to work? Thanks.

**Comment by poshul** [comment]
+1 to this. I see my personal calendar, but not ones shared with my account.

**Comment by jobisoft** [comment]
This never worked. This add-on is using the very simple EAS protocol, which aims at private use. Advanced features like group or shared calendars are not supported by the protocol.

In a recent O365 update, some shared folders are now directly copied into the users accounts and Exchange is keeping them in sync. These folders can be synced by EAS.
