### ISSUE TITLE
Exchange calendar appointments lost after task error

### ISSUE THREAD

**Issue by tigerjack** [jobisoft/EAS-4-TbSync#251]
## Your environment

TbSync version: 4.7
EAS-4-TbSync version: 4.7
Thunderbird version: 115.4.1

## Issue
I had a sync error, apparently related to some task as per [this issue](https://github.com/jobisoft/EAS-4-TbSync/issues/250), that prevented the synchronization of the whole calendar. 
At this point, none of my event was showing in the calendar.
I then unchecked the Task synchronization, and performed a whole sync, that apparently succeeded.
At this point, all of my event were also deleted from my online account.

**Comment by jobisoft** [comment]
Nothing I can do.
