### ISSUE TITLE
Provider for Exchange ActiveSync for Office 365 is disabled

### ISSUE THREAD

**Issue by abdelmaged** [jobisoft/EAS-4-TbSync#252]
## Your environment

TbSync version: 4.7
EAS-4-TbSync version: 4.7
Thunderbird version: 115.4.1 (64-bit)
OS: Window 10 22H2

**Issue:**
I'm trying to add new account of Microsoft Office 365, but after authenticating it gives the following error from ProcessAuth:
```
Sorry, but we’re having trouble signing you in.
AADSTS7000112: Application '2980deeb-7460-4723-864a-f9b0f10cd992'(Provider for Exchange ActiveSync for Office 365) is disabled.

Request Id: 2b6aacef-0edb-4527-b086-7693d8c71700
Correlation Id: 6a84bc5e-8d71-4efd-9569-6118cd227518
Timestamp: 2023-11-06T07:33:09Z
Message: AADSTS7000112: Application '2980deeb-7460-4723-864a-f9b0f10cd992'(Provider for Exchange ActiveSync for Office 365) is disabled. 
```

**Comment by jobisoft** [comment]
Looks like your IT does not like TbSync and has disabled it for the tenant. Not much I can do.
