### ISSUE TITLE
Flagged emails in Outlook are not starred in TB (vice versa is working)

### ISSUE THREAD

**Issue by scollovati** [jobisoft/EAS-4-TbSync#258]
## Your environment

TbSync version:
EAS-4-TbSync version:4.8
Thunderbird version: 115.6.0 (64-bit) on Windows 10

## Expected behavior
When I flag an email in the OWA, the same email should be starred in TB.
The other way round is working fine.

## Actual behavior
Flagged emails are not starred in TB (vice versa is working).

**Comment by jobisoft** [comment]
This add-on is not touching emails. Contacts and Calendars only
