### ISSUE TITLE
My TB115 under Windows 11 was today automatically updated to TB128. Now, EAS-4-TbSync is deactivated. There is no version of this add-on for TB128 yet. Please update it now for TB128.

### ISSUE THREAD

**Issue by jretxaniz** [jobisoft/EAS-4-TbSync#268]
My TB115 under Windows 11 was today automatically updated to TB128. Now, EAS-4-TbSync is deactivated. There is no version of this add-on for TB128 yet. Please update it now for TB128.

_Originally posted by @axelrathey in https://github.com/jobisoft/EAS-4-TbSync/issues/267#issuecomment-2260209289_

**Comment by jretxaniz** [comment]
We are in the same situation. I found a TBSYNC version that works but we need the EAS 
Thank you

**Comment by soumitrachatterjee** [comment]
> We are in the same situation. I found a TBSYNC version that works but we need the EAS Thank you

Same here.

**Comment by jobisoft** [comment]
Dupe of https://github.com/jobisoft/EAS-4-TbSync/issues/267
