### ISSUE TITLE
Existing Outlook events do not appear, only new/edited ones

### ISSUE THREAD

**Issue by martinmagnusson** [jobisoft/EAS-4-TbSync#275]
## Your environment

TbSync version: 4.8
EAS-4-TbSync version: 4.8
Thunderbird version: 115.15.0

## Expected behavior
Adding Outlook Exchange calendar and syncing makes all existing calendar events appear in Thunderbird. 

## Actual behavior
No existing events appear. However, I can add a new event in Thunderbird and it appears in Outlook. Likewise, if I add or edit an event in Outlook, it appears in Thunderbird after the next sync. 

It used to work great until a couple of days ago, when I disabled+enabled my account in TbSync (which I have been able to do without issues in the past). I have tried with my account on two different computers and get the same effect.

**Comment by jobisoft** [comment]
https://github.com/jobisoft/EAS-4-TbSync/issues/266
