### ISSUE TITLE
The EAS server reports <UserDisabledForSync> (status 126) and does not allow TbSync to access you account

### ISSUE THREAD

**Issue by Bamban** [jobisoft/EAS-4-TbSync#36]
Hello,
I have this message when I try to synchronize my account: "The EAS server reports <UserDisabledForSync> (status 126) and does not allow TbSync to access you account"
The message is pretty clear, it seems the problem comes from my Exchange server, but I just wanted to be sure. I just sent the log to you by email.

Thanks !

## Your environment

TbSync version: 0.7.22
EAS-4-TbSync version: 0.7.16
Thunderbird version: 60.3.1

[No ] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/EAS-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Synchronization occurs.

## Actual behavior
Synchronization does not occurs

**Comment by jobisoft** [comment]
Yep, not allowed, get in touch with your IT.

Best regards,
John
