### ISSUE TITLE
Support for DOMAIN\username in Autodiscovery

### ISSUE THREAD

**Issue by digulla** [jobisoft/EAS-4-TbSync#37]
## Your environment

TbSync version: 0.7.22
EAS-4-TbSync version: 0.7.16
Thunderbird version: 60.3.3

## Expected behavior
Accept DOMAIN\username in Autodiscovery in addition to email address.

## Actual behavior
It refuses anything which doesn't look like an email address.

## Suggested fix
Try whatever the user typed into the field. When it works, great.

When it doesn't work, supply a message "Your server probably expects an email address or DOMAIN\username"

## Workaround
Use the custom discovery.

**Comment by jobisoft** [comment]
As far as I know, EAS autodiscover only works, if the user provides something like user@domain.tld, because I have to query a specific endpoint at autodiscover.domain.tld to get the information.

I do not know how this should work with NTDOMAIN/user, because I do not know what to query. 

If you have information on that, please provide. But remember, this is EAS, not EWS.

**Comment by digulla** [comment]
I see. I just noticed that autodiscover with my email address (with local Exchance server) would return HTTP 401. I used copy&paste to avoid typos.

When using custom setup, I had the same problem until I tried DOMAIN\username. I tried that because that's how ExQuilla is set up.

But now, I'm not sure whether I'm missing something important.

Note: I know next to nothing about Exchange, EAS or EWS.

**Comment by jobisoft** [comment]
Ok, exquilla is using the EWS protocol which is Exchange WebServices and the preferred protocol of on premises Exchange servers. These servers also support EAS, which is Exchange ActiveSync and a different protocol. 

I do not think, EAS supports autodiscover via NTDOMAIN/User. It does support authentication with that format. 

Your IT could set up the required endpoint to make EAS autodiscover work with your email and even return the required NTDOMAIN/User string which is needed to authenticate.

I do not think, I can do anything here.

**Comment by digulla** [comment]
Thanks for the clarification.
