### ISSUE TITLE
Feature request: Show additional EAS contact information in contact preview

### ISSUE THREAD

**Issue by Letterus** [jobisoft/EAS-4-TbSync#38]
I can edit additional EAS fields for a contact synced via EAS provider, but those fields are not displayed within the preview of the contact. Would be nice if those were shown as well.

**Comment by jobisoft** [comment]
Would it be enough to have all the phone Numbers? Do you also need "People", "Messaging" and the 3rd Address?

**Comment by Letterus** [comment]
generally speaking it might be confusing that there is data you can edit but not view when you click the contact. but yep, for me phone numbers would be great. thanks :)

**Comment by jobisoft** [comment]
It is part of the beta I released just now. Happy testing :-)

https://tbsync.jobisoft.de
