### ISSUE TITLE
Feature request: Make location input field of a calendar entry support multiple lines

### ISSUE THREAD

**Issue by Letterus** [jobisoft/EAS-4-TbSync#39]
The location information of an entry made by an Apple client application looks like this:

![bildschirmfoto 2018-12-11 um 00 39 21](https://user-images.githubusercontent.com/2911501/49768642-4cb98a00-fcdd-11e8-91c5-8ec710de9088.png)

Would be nice if the input field of the edit dialog would support multiple lines as well. Otherwise it's easy to make mistakes when editing such an entry, f.e. mixing street number and zip code. Currently it's displayed like this:

![bildschirmfoto 2018-12-11 um 00 39 44](https://user-images.githubusercontent.com/2911501/49768648-517e3e00-fcdd-11e8-8daf-ff6d715f3a26.png)

**Comment by jobisoft** [comment]
Ok. Thanks for your feedback.
