### ISSUE TITLE
Deactivate EAS contact book suggestion (or not use it for main suggestions)

### ISSUE THREAD

**Issue by magicvince** [jobisoft/EAS-4-TbSync#42]
Using Linux Mint Debian Edtion 3 (Debian stretch based)

TbSync version: 0.7.22
EAS-4-TbSync version: 0.8
Thunderbird version: 60.3.0

When i began to add a destination address, after 3 letters, the adress bar suggest me EAS contact first and it's very difficult to use autocompletion for adresses stock in other adress books.
I Disable EAS contacts in TBSync parameter but after a reset, there's no change.Is there 

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).Is there a solution to deactivate EAS addressbook or to mix suggestions?
Thanks for your great job

**Comment by jobisoft** [comment]
Feature added in latest beta:
tbsync.jobisoft.de

**Comment by magicvince** [comment]
Sorry, long time to answer. It's not desync adressbook, but only to not to use the suggestion of auto-completion of the EAS. Our company adressbook his full of thousands adresses and when I type part of adress of my reals contacts (stored in other sync our personal adressbook) hundred of eas'adresses foul my search. I would like to list only the adresses mark as my contact in one of adressbook and use eas adress book only in the adressbooks panel.

**Comment by jobisoft** [comment]
What is the adressbook panel?

If you disable EAS autocompletion, they do not show up. Are you talking about the search in the adrressbook? There they only show up, if you search your eas addressbook, not when searching any other.

I did not understand the first sentence:

> It's not desync adressbook, but only to not to use the suggestion of auto-completion of the EAS

Can you give a precise example of where you would like to have EAS GAL results not included? With screenshoot?

**Comment by magicvince** [comment]
Fine, I found.

At first my problem was to deactivate GAL auto-completion, but I haven't found the TBsync Options (I take a lot of time to detect that TBsync Options was in Edition Menu (I've search in extensions menu).
Thanks for your assistance.(sorry for by ugly sentence in the previous message). Here's the screenshot for other persons searching this option.
![thunderbirdeassolved](https://user-images.githubusercontent.com/627273/53603780-dc6f2600-3bb2-11e9-9150-1c805b2797f7.png)
Just uncheck this option :)
