### ISSUE TITLE
How to sync only calendar but not address book?

### ISSUE THREAD

**Issue by patrick258** [jobisoft/EAS-4-TbSync#47]
I am connected to a slow exchange server at work that has a huge address book.
Every time I am creating a new email, at each character that I am typing in the to address, my computer hang for 10s to search for match in the exchange company address book.

How can I disable the contact feature for an account, but keep only the calendar synch?
The only option I see is to not synchronize my personal company contact book, but this one is small. I don't see the /GAL address book displayed.

Also Thunderbird address book menu does not give option to disable a specific address book for the search. Even if I disable the search local address book in the general option, it will still search the exchange GAL address book linked through TbSync/EAS

**Comment by jobisoft** [comment]
That feature has been added in the latest beta:
https://github.com/jobisoft/EAS-4-TbSync/issues/42

You can disable EAS auto complete in the options now, and he will not enable any resource by default. 

Ask if something is unclear.

To install beta: Install all(!) XPI modules found here:
https://tbsync.jobisoft.de/beta

**Comment by jobisoft** [comment]
Also, there is a performance bug in TB 60.3 which has been fixed in 60.4. maybe that fixes your problem altogether.
