### ISSUE TITLE
JavaScript error

### ISSUE THREAD

**Issue by iron-viper** [jobisoft/EAS-4-TbSync#49]
## Your environment
Ubuntu 18.04 64-bit
![selection_006](https://user-images.githubusercontent.com/1132974/51230136-0ad0d300-1970-11e9-9a6d-d1d7e9168c74.png)

TbSync version: -
EAS-4-TbSync version: 1.0.2.3
Thunderbird version: 60.2.1 64-bit

[* ] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/EAS-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Normal sync

## Actual behavior
I have an error with sync. Log look like this:
`eas.cachedTimezoneData.iana[eas.cachedTimezoneData.abbreviations[parts[i]]] is undefined

guessTimezoneByStdDstOffset@chrome://eas4tbsync/content/provider/eas/tools.js:219:1
setThunderbirdItemFromWbxml@chrome://eas4tbsync/content/provider/eas/calendarsync.js:50:48
eas.sync.processCommands<@chrome://eas4tbsync/content/provider/eas/sync.js:468:25
TaskImpl_run@resource://gre/modules/Task.jsm:326:42`
## Steps to reproduce
Run sync with Exchange server

Email with debug.log was sent.

**Comment by jobisoft** [comment]
Can you update your AddOns to get the latest beta and try again?

**Comment by iron-viper** [comment]
@jobisoft Big thx for your speed! Now it's work correctly.
