### ISSUE TITLE
Notes read and write

### ISSUE THREAD

**Issue by sinya13** [jobisoft/EAS-4-TbSync#53]
Hello John!

Is it possible to make such functionality in the plans? This applies equally to EAS-4-TbSync and DAV-4-TbSync. There is a Notes folder on the Exchange server. Reminders are stored there. This is a personal notepad for text entries. Is it possible to teach EAS-4-TbSync and DAV-4-TbSync synchronize the Notes folder? And then write a small addition as a CategoryManager (for example, NotesManager). That will be able to write and read reminder messages for all managed accounts! MS Outlook knows how, Linux Evolution can, but Thunderbird does not! But it is sometimes necessary! Notes is especially valuable when quickly recording from your mobile phone valuable information of a solid view on the go! So at least Appple ifons work correctly with the Notes Exchange Exchange servers folder!

**Comment by jobisoft** [comment]
I see the need, but I am packed with work. If someone else adds a well integrated notes manager to lightning, i can sync into, ping me back. But even then I cannot promise to work on this.
