### ISSUE TITLE
Separate GAL book among the address book tabs

### ISSUE THREAD

**Issue by sinya13** [jobisoft/EAS-4-TbSync#55]
Hello Johh!

Could you in the future add a separate GAL book among the address book tabs? Sometimes there is a situation when we need to quickly look at the entire list of the GAL address list of the server to make a decision! A personal book contacts and offered contacts are often generally empty, we don't love them. This solution probably will not require big changes, but it will greatly help users! Thanks!

**Comment by jobisoft** [comment]
The GAL can only be searched, like LDAP. I cannot provide „the full list“.

**Comment by sinya13** [comment]
But after all, Outlook It somehow does through its EAS-EWS connection ...

**Comment by jobisoft** [comment]
I do not know what EWS is doing but the EAS implementation only has a search API and that search API ignores search requests shorter than 3 chars. I do not see how I can get the full list, it is not supported bei EAS.

**Comment by sinya13** [comment]
It's a pity...

**Comment by KIAOman2020** [comment]
> The GAL can only be searched, like LDAP. I cannot provide „the full list“.

Hi @jobisoft , how I can search GAL? I'm using Tbsync 2.12 Exchange Activesync with TB68. I can see personal contacts & suggested contacts under Address Book tab but can't see GAL. Also if write new email To field is not searching in GAL.
