### ISSUE TITLE
Javascript Error - eas.defaultTimezoneInfo is null

### ISSUE THREAD

**Issue by kiltum** [jobisoft/EAS-4-TbSync#56]
os x mojave

TbSync version: 1.5
EAS-4-TbSync version: 0.10.3
Thunderbird version: 60.5.0 64

[ * ] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/EAS-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Sync calendar events well 

Or produce error message like "Set timezone in lighting before!"

## Actual behavior

When i try sync calendar events from company exchange, i got JavaScript Error

eas.defaultTimezoneInfo is null

setThunderbirdItemFromWbxml@chrome://eas4tbsync/content/provider/eas/calendarsync.js:33:13
eas.sync.processCommands<@chrome://eas4tbsync/content/provider/eas/sync.js:548:25
TaskImpl_run@resource://gre/modules/Task.jsm:326:42

## Steps to reproduce
1. Install fresh thunderbird (or clean up .thunderbird folder - i think it will same effect)
Thunderbird - Preferences - Calendar - General

Do not touch timezone / LEAVE timezone field empty 

2 . Just to try to make a first sync with exchange

**Comment by jobisoft** [comment]
I cannot reproduce that on windows, as there it always picks a timezone. However I try to catch this now. Can you switch to the beta release channel and try again?

Follow instructions given here:
https://tbsync.jobisoft.de

After you have synced and the error still happens, please check the error log for details:

![image](https://user-images.githubusercontent.com/5830621/52710268-39ea5c80-2f8f-11e9-8768-c35a08878b32.png)

**Comment by kiltum** [comment]
yes, for my case its not appear anymore

**Comment by jobisoft** [comment]
thanks for your feedback
