### ISSUE TITLE
Invite attendees view doesn't autocomplete from EAS source directory

### ISSUE THREAD

**Issue by pd5rm** [jobisoft/EAS-4-TbSync#57]
## Your environment

TbSync version: 1.5
EAS-4-TbSync version: 0.10
Thunderbird version: 60.5.0

[X] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/EAS-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior

I would expect I could autocomplete names when I enter there names in the "Invite Attendees" view. However, it's only completing names from personal or LDAP sourced lists.

## Actual behavior

It would be nice to use the EAS sourced names for autocomplete.

## Steps to reproduce

1. Create new event in calendar.
2. Choose Invite attendees from button or menu.
3. Start typing a known existing name, expecting to autocomplete.
4. Observe that name autocomplete never pops up.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Implemented in latest beta
https://tbsync.jobisoft.de

However, the source of the autocompleted contact is not shown (as in the message composer), I do not know how to enable that.
