### ISSUE TITLE
Thunderbird Tasks not syncing with Outlook.com Tasks.

### ISSUE THREAD

**Issue by Edward-2** [jobisoft/EAS-4-TbSync#60]
Environment: Windows 7 Pro SP 1, 6GB RAM, 64Bit, i3-2120

TbSync version:  1.7
EAS-4-TbSync version:  0.12
Thunderbird version:  60.7.0 (32Bit)

[X ] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/EAS-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Tasks created in Thunderbird should sync to and display in Outlook.com account.

## Actual behavior
Can view the tasks created using the Outlook.com web app and the Microsoft To-Do iOS app in Thunderbird. But the tasks created in Thunderbird are not syncing-to or displaying in Outlook.com account.

## Steps to reproduce
Create a new Task in Thunderbird.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by kmyid** [comment]
Hello, I'm seeing a similar behaviour after upgrading to TB 68. I can sync from EAS, but not the other way around. I'm using 

TbSync version: 2.4
EAS-4-TbSync version: 1.3
Thunderbird version: 68.0 (64bit) OSX

**Comment by jobisoft** [comment]
What is the error you get?

**Comment by kmyid** [comment]
There are no error messages actually. TB Sync thinks the sync was successful. I've looked at the debug.log, and there's nothing really particular.

**Comment by jobisoft** [comment]
Found the error. Fixed in Beta for TB68:
https://tbsync.jobisoft.de

**Comment by kmyid** [comment]
It works now in 1.4!

**Comment by jobisoft** [comment]
Yes, it got released very quickly. Thanks for your feedback.
