### ISSUE TITLE
Java Error with beta 0.12.7

### ISSUE THREAD

**Issue by plague-doctor** [jobisoft/EAS-4-TbSync#62]
## Your environment

TbSync version: Beta 0.7.6 (2019-07-22 15:56)
EAS-4-TbSync version: Beta 0.12.7 (2019-07-22 15:56)
Thunderbird version: 60.8 Linux

[/] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/EAS-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

Latest beta throws an error while synchronizing: 
```
tbSync.getString is not a function
updateFailedItems@chrome://eas4tbsync/content/provider/eas/sync.js:644:68
processResponses@chrome://eas4tbsync/content/provider/eas/sync.js:693:29
```

**Comment by jobisoft** [comment]
Indeed. Can you try EAS 0.12.8 (just force update in AddonManager). Fixed?

**Comment by jack-movember** [comment]
Fixed :-) Thanks

**Comment by jobisoft** [comment]
thanks for reporting that.
