### ISSUE TITLE
Sync fails for recurring event with error: [Bad item skipped <Invalid item!>]

### ISSUE THREAD

**Issue by orende** [jobisoft/EAS-4-TbSync#65]
## Your environment

TbSync version: 0.7.22
Thunderbird version: 60.2.1 (64-bit)
Provider for Exchange ActiveSync: 0.9

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Syncing a calendar with a recurring event should work.

## Actual behavior
Syncing fails with an error message.

## Steps to reproduce
1. Add recurring event of the type shown in the debug log
2. Sync calendar with outlook.office.com

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

[tbsync_error_log.txt](https://github.com/jobisoft/TbSync/files/2791885/tbsync_error_log.txt)

**Comment by SergeLalonde** [comment]
I get the error:
   The EAS server did not accept 3 elements.
Is there a way to clear the errors? 
Or do I have to delete the calendar events that are causing the problem?
Thanks!

**Comment by jobisoft** [comment]
I have a report, that this issue is fixed in the latest beta. Could you verify?
https://tbsync.jobisoft.de
