### ISSUE TITLE
Failed to sync calendar and tasks in TB68 with Zimbra server

### ISSUE THREAD

**Issue by fluminea** [jobisoft/EAS-4-TbSync#67]
## Your environment

TbSync version: 2.3
EAS-4-TbSync version: 1.2
Thunderbird version: 68

[ X ] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/EAS-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
AS for the precedent version for Thunderbird 60.x, i'd like to synchronize my contacts, tasks and calendar

## Actual behavior
Contacts seem to be OK. 
Synchronize tasks and calendar is OK from online to local but not the reverse. 

## Steps to reproduce
The server is a Zimbra 8.8.11

Configure the addon and synchroinze the items you want
Create a new item in calendar and synchronize -> error 500
Create a new task and synchronize -> sometimes OK, and sometimes error 500

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Cannot do much about an http 500 error.

You could increase the userdata level to 9 to have more data in the log, by changing this in the Advanced Thunderbird Configuration:

extensions.tbsync.log.userdatalevel

The other thing you need to make sure is, that you actually created the task inside the "Task" folder of your Zimbra account.
https://github.com/jobisoft/EAS-4-TbSync/wiki/Error:-Bad-item-skipped

**Comment by fluminea** [comment]
Hi.
It seems to work with the new version on my test machine.
Thanks for your work !

**Comment by jobisoft** [comment]
Perfect!
