### ISSUE TITLE
Calendars from personal favorites are not showing up

### ISSUE THREAD

**Issue by Xnyle** [jobisoft/EAS-4-TbSync#69]
## My environment

TbSync version: 2.4
EAS-4-TbSync version: 1.5
Thunderbird version: 68.0

No, I have not installed the latest available (beta) version and I highly doubt that would change anything:

## FR

Our EWS Server has some public calendars on it. I know EAS is using OWA and not EWS protocol. 
BUT after adding those calendars as personal favorites via Outlook those calendars also appear in the OWA web frontend so theoretically there should be a way to access them via EAS plugin as well.

Is there any chance to extend EAS in order to at least show calendars from personal favorites?

If so what kind of further information is needed?

**Comment by jobisoft** [comment]
I show everything I can see. If it is not shown, it is not accessible.

The Office 365 backend is doing some tricks to map shared calendars into EAS, but on prem EWS usually does not do that.

John

**Comment by Xnyle** [comment]
Well, if the web frontend can see it, it must be accessible in some way and it is:

I tried to dig into the XHR requests the frontends sends:

service.svc?action=GetCalendarFolders&EP=1&ID=-7&AC=1

returns one entry under CalendarFolders (I guess that's my default calendar)
but it returns two entries under CalendarGroups the second one has two calendars. One of them is the one I'm missing.

It then sends two requests for both calendars
service.svc?action=GetCalendarView&EP=1&ID=-10&AC=1
service.svc?action=GetCalendarView&EP=1&ID=-8&AC=1

I don't want to post the responses here (no idea what kind of secrets are in there) but I could send them if you like.

**Comment by jobisoft** [comment]
This request is not an EAS request. What you are seeking is not accessible via EAS.

The TbSync provider interface is open and you can build an OWA provider. I am currently putting the documentation together here: 

https://tbsync.readthedocs.io

The later chapters are not done yet, hope to have it finished by end of this month.

**Comment by raulpardo** [comment]
In case this helps, I noticed that if you add Exchange calendars in the Android app, then they are visible by EAS-4-TbSync.
