### ISSUE TITLE
Not synchronising with Exchange 14.3.123.0

### ISSUE THREAD

**Issue by grahamperrin** [jobisoft/EAS-4-TbSync#70]
## Your environment

TbSync: 2.4
EAS-4-TbSync: 1.5
Thunderbird: 68.1.0 (64-bit)
OS: FreeBSD-CURRENT
Mailbox server Microsoft Exchange version (reported by OWA): 14.3.123.0

[✓] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/EAS-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior

An appointment added using Thunderbird, with an optional attendee, should: 

- be visible in OWA; and 
- I guess, have a related item in the Sent Items folder

## Actual behavior

Not visible in the OWA calendar of the sender (organiser); no invitation in the OWA Inbox of the attendee; no related item in the Sent Items folder of the organiser. 

## Steps to reproduce

1. draft an appointment (my personal Exchange account, gjp4)
2. add an attendee (a shared account, bs59 a.k.a. bbsadmin)
3. make the attendee optional
4. save and close. 

Debug log to follow; I'll delete the appointment from Thunderbird then aim to reproduce the issue.

**Comment by grahamperrin** [comment]
PEBKAM? 

I had used the **Synchronise calendars** context menu item for the calendar, in the Calendar tab, without realising that the account was set to never synchronise. 

Is 0 (zero) minutes the default for periodic?

Do the synchronise commands in the Calendar tab **not** cause a sync of Provider for Exchange ActiveSync? 

----

> … no invitation in the OWA Inbox of the attendee; …

Now I see, <https://github.com/jobisoft/EAS-4-TbSync/wiki/About:-Provider-for-Exchange-ActiveSync>: 

>> - sending or responding to meeting invitations is not fully working

Worked around by using OWA to send an update to the meeting.

**Comment by jobisoft** [comment]
As suggested in your other issue, I will put the know issues (including the non-working sync buttons) on the addon page.

0 setting is for no sync. If you set it to 5, it will sync every 5 minutes.

**Comment by grahamperrin** [comment]
Noted with thanks, from <https://addons.thunderbird.net/addon/eas-4-tbsync/#addon-description>: 

> - Lightning sync buttons do not trigger a sync of EAS calendars
> 
> To mitigate push sync and the failing sync buttons, set an auto sync interval of 10, to auto sync your account every 10 minutes.
