### ISSUE TITLE
Make known issues known at addons.thunderbird.net

### ISSUE THREAD

**Issue by grahamperrin** [jobisoft/EAS-4-TbSync#71]
From <https://github.com/jobisoft/EAS-4-TbSync/wiki/About:-Provider-for-Exchange-ActiveSync>: 

> … some features have not yet been implemented:
> 
> - sending or responding to meeting invitations is not fully working
> - push sync

Can you list known issues, such as those, at <https://addons.thunderbird.net/thunderbird/addon/eas-4-tbsync/>?

Thanks

**Comment by jobisoft** [comment]
Done.

**Comment by grahamperrin** [comment]
Thanks!
