### ISSUE TITLE
current beta not working at all with 70.0b2 (64-bit)

### ISSUE THREAD

**Issue by n8v8R** [jobisoft/EAS-4-TbSync#81]
## Your environment

OS: W10 Pro x_64 v1903 b18362.388

TB: 70.0b2 (64-bit)

TbSync version:
EAS-4-TbSync version: current beta (1.5.7)
Thunderbird version: current beta (2.4.18)

[X] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/EAS-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

The WX's debug log cannot be produced since its UI is not opening, the console printing

> TypeError: TbSync.manager is undefinedaccountManager.js:21:5
>     onunloadoptions chrome://tbsync/content/manager/accountManager.js:21
>     onunload chrome://tbsync/content/manager/addonoptions.xul:1

No sync at all with the remote node.

**Comment by jobisoft** [comment]
Did I wrote anywhere, that is should?

**Comment by n8v8R** [comment]
My bad, wrongly assuming that feedback is favoured.

**Comment by jobisoft** [comment]
Thanks for your feedback.

I just wanted to make sure, I did not write anywhere, that I actually keep up with Thunderbird Beta, as I do not have the resources to follow these changes in such a tight schedule.
