### ISSUE TITLE
Reminders keep coming back after each synchronization

### ISSUE THREAD

**Issue by illuminated** [jobisoft/EAS-4-TbSync#83]
## Your environment

TbSync version: 1.7.0.2
EAS-4-TbSync version: 0.12
Thunderbird version: 60.9
OS: Linux Mint 19.2

Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/EAS-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
After calendar synchronization, if any event reminder is dismissed, it should not appear again.

## Actual behavior
After each synchronization the reminder popup keeps opening for the events in the past that have been already dismissed.

Just to note: other email clients with Exchange/Activesync support (like Evolution or MS Outlook v2016) correctly interpret the "dismiss" action and do not show same reminders after they have been dismissed once.

## Steps to reproduce
Install TBSync and Activesync provider, add an Exchange account (in my case: hosted by Kolab Groupware).

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

[debug.log](https://github.com/jobisoft/EAS-4-TbSync/files/3707490/debug.log)

**Comment by jobisoft** [comment]
Is this still valid with TB68?

**Comment by jobisoft** [comment]
I am not able to store the ACK state of an event back to the server and I also cannot read it. What I do now ist to programatically ACK all incoming events whose start date is in the past.

Does that solve your issue? It is included in the latest beta for TB68:
https://tbsync.jobisoft.de

**Comment by jobisoft** [comment]
Does that solve your issue?
