### ISSUE TITLE
calendar syncs only previous 6 months 

### ISSUE THREAD

**Issue by WDenda** [jobisoft/EAS-4-TbSync#85]
## Your environment
W10 Pro 64bit 
TbSync version: 1.7.9 b 2019-08-12
EAS-4-TbSync version: 0.12.9 b 2019-08-12
Thunderbird version: 60.9.0 64bit

[X] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/EAS-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Calendar should sync all 2500 appointments from 2008 onwards in this calendar as I remember this happened on my Linux machine.

## Actual behavior
Calendar syncs only appointments from April 2019 onwards

## Steps to reproduce
I set up my live.de account username password, activate account

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).
Done

**Comment by jobisoft** [comment]
Fixed in 2.x branch for TB68, there you have a selector in your account options. 

In 1.7.x you need to follow this:
https://github.com/jobisoft/TbSync/wiki/Advanced-configurations#options-for-exchange-activesync

**Comment by WDenda** [comment]
Aahhhh, ok.

Thank you very much. Sorry, I only took a look into EAS-4-Tbsync Wiki.

I do wait for TB68 update until it is ready, because right now it does
not work on my PC (blank window). Until then, I'll use these Advanced
Configuration settings in TB60.x

Am 14.10.2019 um 11:12 schrieb John Bieling:
>
> Fixed in 2.x branch for TB68, there you have a selector in your
> account options.
>
> In 1.7.x you need to follow this:
> https://github.com/jobisoft/TbSync/wiki/Advanced-configurations#options-for-exchange-activesync
>
