### ISSUE TITLE
Microsoft removing support for EAS basic auth -- will EAS-4-TBSync support Oauth2?

### ISSUE THREAD

**Issue by David-S-Morgan** [jobisoft/EAS-4-TbSync#87]
## Your environment

TbSync version: 1.7.0.2
EAS-4-TbSync version: 0.12
Thunderbird version: 60.9.0 (Xubuntu 16.04 LTS 64-bit)

[ ] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/EAS-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
EAS-4-TBSync will be able to authenticate using OAuth 2.0 Tokens

## Actual behavior
I don't think this is currently supported

## Steps to reproduce
N/A

Hi,

On September 20, 2019, Microsoft announced that they will be discontinuing support for basic auth for Exchange ActiveSync (and POP/IMAP/PowerShell), starting on October 13, 2020:

https://techcommunity.microsoft.com/t5/blogs/blogarticleprintpage/blog-id/Exchange/article-id/27095

Is there a plan to support OAuth2-based authentication? I didn't see any open/closed issues related to this, and in a quick search of the source code for EAS-4-TBSync I didn't see any refs to oauth, but apologies if I missed something and this has already been discussed or implemented.

Thanks for providing this and the related add-ons for TB.  I'm a Linux guy and it's nice to be able to access the O365 exchange calendar without having to jump into the web interface!

**Comment by jobisoft** [comment]
Thanks for the heads up. I have looked at OAUTH once and have failed to grasp its implementation concept. Can you contribute or help to figure that out?

**Comment by David-S-Morgan** [comment]
I'm happy to help if I can.  I'm more of a manager these days, but have
coded a bit (mostly Python and bash scripting, with a bit of C way back),
and could try taking a look.  Any pointers you have regarding code
documentation and the auth stuff you are currently using would be helpful.

**Comment by jobisoft** [comment]
The language used to code this does not matter at this point, it is more about what type of http request have to be send/prepared to get token.

I once looked at google and there it looked like I had to register myself as a service provider at google to be able to get tokens for their different APIs. How is this with Microsoft EAS? I have no documention and no resources. If you could dig though that, it would help me a lot.

**Comment by David-S-Morgan** [comment]
Sure -- let me read up on it a bit and get back to you.  I should have some
time this weekend.

**Comment by David-S-Morgan** [comment]
FYI, was just doing a quick search and ran across this article.  It's from 2014, but seems to lay out at a high level what is necessary to use OAuth2 with O365.  You would have to register with MS as part of the process.

 https://blogs.msdn.microsoft.com/exchangedev/2014/03/25/using-oauth2-to-access-calendar-contact-and-mail-api-in-office-365-exchange-online/

More info when I have it.

**Comment by jobisoft** [comment]
Be sure to check for EAS (ActiveSync) which is different from EWS (WebServices)

**Comment by David-S-Morgan** [comment]
Ah, got it.  Thanks.

**Comment by jobisoft** [comment]
Some Resources I found:
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols-oauth-code
https://oauthplay.azurewebsites.net/

**Comment by David-S-Morgan** [comment]
Thanks

**Comment by jobisoft** [comment]
ok, I think this is what needs to be implemented: 
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow

I did register an app with Microsoft now, my ClientID is 2980deeb-7460-4723-864a-f9b0f10cd992

**Comment by jobisoft** [comment]
It looks like that is the URL I need to use in the dirst step popup. After login, the redirected page has a code parameter which appears to be the token.

https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize?response_type=code&client_id=2980deeb-7460-4723-864a-f9b0f10cd992&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient&prompt=consent&scope=2980deeb-7460-4723-864a-f9b0f10cd992/.default

**Comment by David-S-Morgan** [comment]
Yup, that link works for me and I get what I suppose is the authorization
token.  I'm already signed in to my work email, but after selecting that
account, I get a list of permissions to accept (attached screenshot).  Next
step would be to submit that token and client_id to get the access and
refresh tokens, right? (I also just tried that link in an incognito window
and it does take me to my organization's SSO sign-in page like it should.)

**Comment by jobisoft** [comment]
Yes, you should be able to manually extract the authorization code and create the url to get the access token. If this all works without cookies, I could hack TbSync to check an advanced preference where you can set your access token and Tbsync will use that instead of basic auth.

**Comment by David-S-Morgan** [comment]
Sounds like that should be pretty straightforward.  I will test it out soon.

**Comment by jobisoft** [comment]
I was able to access my o365 account with a bearer token via TbSync! So it works in generall. However, there is a lot to do, until this is ready to ship. Currently almost everything is hardcoded, but I should be able to detect the endpoints. I keep you updated.

**Comment by David-S-Morgan** [comment]
Excellent! I tried crafting the URL to get the bearer token using Postman
to craft the URL, but I got an error message when I sent the POST with a
status like "grant_invalid" (or something along those lines -- I don't
completely remember).  Clearly I was doing something wrong, but didn't have
much time to look into it further.

It sounds like this is under control, but if there is anything I can do to
help, let me know.  I could certainly test any alpha/beta code if needed.
Microsoft isn't turning off basic auth for EAS until next October, so there
is enough time.

**Comment by jobisoft** [comment]
As this is not urgent, I take the longer route and make this a general feature of TbSync, so it can be reused to do oauth for google.

I am currently only able to auth against O365 accounts, not against plain Microsoft Accounts like something@outlook.com. I added my current status to the back of this issue:
https://social.msdn.microsoft.com/Forums/sqlserver/en-US/3fab6bc8-ff29-4f82-888f-1b8f0201d4af/what-is-the-scope-to-use-oauth20-on-exchangeactivesync-protocol-for-personal-microsoft-accounts?forum=WindowsAzureAD&prof=required

**Comment by David-S-Morgan** [comment]
If I understand that thread correctly, it doesn't sound like this is going
to work for consumer outlook.com/.de accounts -- which leads me to wonder
if basic auth will continue to work for such accounts in the future.
Certainly seems like that would be the case, if they don't actually support
Oauth2 for such accounts!

**Comment by jobisoft** [comment]
I just released a new beta with OAUTH2 support for O365. I would kindly ask you to test it thoroughly.
https://tbsync.jobisoft.de

If you switch to beta in your current profile, TbSync should automatically switch from basic auth to oauth and ask for your permission the next time you sync. You can also create a new Thunderbird profile and install the beta there and do not touch your working profile. 

The setup wizard no longer has a passwort field and detects wether you are trying to setup an O365 account or something else. It will either pop a OAUTH permission window or a standard password prompt.

That does make the setup for non O365 accounts a bit more ugly I think, but I have no idea how to make the wizard nicer. I should not ask for a password, if Oauth is possible, but I only learn that during discovering.

Feedback is welcome.

**Comment by David-S-Morgan** [comment]
Sure, I am happy to give it a try when I get the time -- might be a day or
two.  I've been holding off upgrading Thunderbird and TbSync -- I'm still
on TB 60.9, so I'll have to take care of that first.

**Comment by fleskesvor** [comment]
I tried to test it, but the beta extensions seems to only be available for Thunderbird 68+, which currently is not available for Ubuntu 18.04. Since this is my work computer, I prefer to stick with the LTS versions, but I'll give it a try on my home computer as soon as possible.

**Comment by jobisoft** [comment]
Well TB60 is almost EOL (grace period). TB68 is the current version. Why is ubuntu not updating their repositories?

**Comment by David-S-Morgan** [comment]
That is a very good question.  According to this thread (
https://discourse.ubuntu.com/t/thunderbird-68/12377/5) 68 is supposed to be
coming to all supported distros, including the one I use, Xubuntu 16.04.
Not sure what happened.

**Comment by David-S-Morgan** [comment]
Just fired up a new Xubuntu 19.10 VM (which includes TB 68.1.2) and
installed the beta XPIs.  Long story short, it works! As soon as I forced a
sync, a nice popup came up with my provider's SSO sign-on page.  Signed in
and the sync continued.  Will poke around a bit and see if I can break it,
but looking good so far.

**Comment by jobisoft** [comment]
PLease update your beta updates (simply let Thunderbird search for addon updates). There was a big in the token refresh code.

**Comment by zigi004** [comment]
hello,
 i can see it switched to ADAL/OAUTH, but it does not work for me.
We are using SAML/shibboleth authentication, it opens login windos and redirect back to o365. I have to grant some permisions:


Permissions requested
Provider for Exchange ActiveSync for Office 365
tbsync.jobisoft.de
This app would like to:
Maintain access to data you have given it access to
View your basic profile
Access your mailboxes

and then this error is displayed:

 Request Id: 1a107add-3ebe-4d3e-b1df-53608c662000
Correlation Id: 6c23a864-ab22-4175-85cf-8c04c3831da1
Timestamp: 2019-11-15T17:29:47Z
Message: AADSTS165000: Invalid Request: The user session context is missing. Do not copy the user context values (cookies; form fields; headers) between different requests or user sessions; always maintain the ALL of the supplied values across a complete single user flow. Failure Reasons:[Missing session context cookie;Token values do not match;]
Advanced diagnostics: Enable
If you plan on getting support for an issue, turn this on and try to reproduce the error. This will collect additional information that will help troubleshoot the issue.

**Comment by jobisoft** [comment]
@zigi004 : Could I have a test account on your server?

**Comment by zigi004** [comment]
yes, how can i share credentials? it will take couple of minutes for synchronisation prepares your account.

**Comment by jobisoft** [comment]
Via E-Mail: john.bieling@gmx.de

**Comment by David-S-Morgan** [comment]
I updated the extensions and have been leaving TB running in the VM.  No
auth issues so far and everything seems to be working fine.

**Comment by jobisoft** [comment]
@zigi004 : As I wrote you via email, it works for me. But I could trigger the behavior you see by disallowing cookies (the error message you send me actually said something about cookies, so I just gave it a try).

Can you confirm, that it works for you as well, when you enable cookies in Thunderbird?

![grafik](https://user-images.githubusercontent.com/5830621/68969640-be4f6180-07e5-11ea-9e01-26b2cce6d712.png)

**Comment by DavidBE-UK** [comment]
Does this OAUTH2 work mean syncing with gmail.com Google Contacts with DAV-4-TbSync should be coming soon? To me, Thunderbird's lack of ability to sync one address book with both a gmail.com Contacts and an outlook.com People through one consistent interface like TBSync is Thunderbird's single biggest lack - including of anything lacking in the main program, never mind extensions.

**Comment by jobisoft** [comment]
@DavidBE-UK : Yes, I plan to do this next.

**Comment by fleskesvor** [comment]
I installed Thunderbird v68 via Flatpak on Ubuntu 18.04, and have tried to setup both of my Office 365 accounts, with varying degrees of success.

On the first one, setup goes extremely smoothly, but when it tries to sync, nothing is synced, failing with the error `status.folderSync.141`. Is there some additional logging I can provide that will make it easier to debug this one?

On the other one, I'm blocked before I can even log in, with a message saying "Provider for Exchange ActiveSync for Office 365" needs admin approval. I think this might be caused by a recent change in my organization, where we can only add whitelisted apps via myapps.microsoft.com, so I'll have to ask for it to be whitelisted. Is this app likely to be the same app when it leaves beta, so that I don't have to ask them for approval multiple times?

**Comment by jobisoft** [comment]
@fleskesvor : Strange that you saw that 141 error. It means that your service provider / IT department request "provisioning" which I enable upon request. But it should do that silently. Strange.

Regarding the approval: yes, the tenant admin can do that and you would need to ask him to grant access. If an admin user tries to access my app, he gets something like this:

![grafik](https://user-images.githubusercontent.com/5830621/68990200-afea5f80-0850-11ea-8826-f7f08dea6347.png)

And can enable the checkbox at the bottom. I probably have to publish some sorts of terms to fulfill your companies requirements. I have no idea what to put there, as I do not do anything with the data beyond what you would expect me to do. Maybe your company can even help me to come up with some sort of terms?

And yes, as soon as I push this from beta to stable, all TbSync users will be switched to OAuth2 access for Office365. But it looks like I need to add an option to not do that? But it somehow does not make sense to stay with the old auth style, because that actually gives me much more power over your account (as I have access to your password) and it is much more insecure.

**Comment by jobisoft** [comment]
@DavidBE-UK : 

**Tada:** The latest beta has google support! You now can now setup the sync of your google contacts and your google calendars from one single UI!

The issue for google is here:
https://github.com/jobisoft/DAV-4-TbSync/issues/56

You can get the beta here: 
https://tbsync.jobisoft.de

![grafik](https://user-images.githubusercontent.com/5830621/69188445-d80de300-0b1c-11ea-8723-811d0dd5b0b3.png)

**Comment by jfdahl** [comment]
Once a distro version has been finalized, the official packages are not updated for features... only for security patches. If you want later versions of official packages, you need to make sure your apt-get configuration includes the "Backport" repos. This is for new software that has been back-ported to older distro versions.

**Comment by fleskesvor** [comment]
@jobisoft Thanks for the information. I will try to figure out who handles these kinds of things at the companies I work for, and see if they need something specific in those terms you set.

**Comment by David-S-Morgan** [comment]
Thanks -- good to know! I do have backports enabled, but perhaps that
package hasn't been released to that channel yet, or perhaps it won't be.
At any rate, I'm not in a hurry to upgrade, but I'm sure I can find a PPA
if I want to go that route.

**Comment by fleskesvor** [comment]
Another question: Does this version of the plugin actually use ActiveSync in any way, like the name and description of the integration suggests? A preliminary feedback I got from one of the companies, said they are highly skeptical of allowing any ActiveSync integrations, since it has been deprecated for a while, and is considered a bad option. If the OWA integration is completely separate from that, I think it would be better if that dialog said "Provider for Outlook Web Access for Office 365" instead.

**Comment by jobisoft** [comment]
This is a pure ActiveSync Addon. I am not doing anything else. And EAS is far from being deprecated. It is the only mobile sync protocol from the exchange family. I just happen to need it on my desktop system.

If it would be deprected, Microsoft would not invest any time into making it ready for OAUTH.

The only thing deprecated is its BASIC Auth implementation. Which is indeed unsafe.

**Comment by fleskesvor** [comment]
It sounds like I must have misunderstood their concerns. It was probably basic authentication specifically, in that case. 🤔

**Comment by jobisoft** [comment]
They can disable just the Basic Auth but let users still use EAS via OAuth. TbSync for Thunderbird 68 supports that now.

https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online

**Comment by jimbaxter** [comment]
My work has just moved everything over to a new Office 365 server and I am now getting the error _"(Provider for Exchange ActiveSync for Office 365) is disabled"_ am I correct that this means I can no longer use TBSync?

I was going to create a new issue but from what I understand above I think this only works with ActiveSync.

**Comment by jobisoft** [comment]
You have to check with your IT / office365 tenent admin, for why they disabled it. Could be that they disabled all 3rd party apps.

**Comment by jobisoft** [comment]
TbSync/EAS is using ActiveSync with Oauth2, if you select the modern auth option during account setup.

**Comment by jimbaxter** [comment]
Yes I selected the "Microsoft Office 365" option.
