### ISSUE TITLE
Meeting stuff: will it be moved out "postponed" status any time soon?

### ISSUE THREAD

**Issue by sten13** [jobisoft/EAS-4-TbSync#97]
## Your environment

TbSync version: 2.10
EAS-4-TbSync version: 1.10
Thunderbird version: 68.4.1

[ ] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/EAS-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
I should be able to notify people about events

## Actual behavior
I cannot notify people: the checkbox is greyed out

## Steps to reproduce
Create an event, then invite attendees. See the "notify attendees" checkbox greyed out.

The issues concerning "meeting stuff" have been labeled "postponed" since Nov 5, 2018. Actually, I don't mind this at all. I'd just like to know whether this will be worked on, because if not, I will have to look for another solution.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by sten13** [comment]
For some reason, there was no email address set under "Calendar Properties", which I did not see at first. Now I can notify attendees, or at least I can click "send and close".

I am very sorry for raising a non-issue. Feel free to close this issue and I will come back if I have anything real to report.

**Comment by jobisoft** [comment]
The initial question is still valid: Will I work on this?

I want to get all the meeting stuff right and it currently is only working partially and I cannot give support on this. I am booked with other things till June 2020, but after that I am activly looking for sponsors/funding so I can work in this full time.
